### ISSUE TITLE
Use Emojione SVG .odt instead of Android .ttf font in "Colorful emojis on Linux" wiki page

### ISSUE THREAD

**Issue by nidico** [wireapp/wire-desktop#1007]
The [Colorful emojis on Linux](https://github.com/wireapp/wire-desktop/wiki/Colorful-emojis-on-Linux) wiki page currently proposes to download the Android .ttf file.

Instead, on Desktop Linux, the SVG .otf file (or maybe also the .woff/2) is preferred. (actually, which exact?)

@mythsunwind: If you agree, can you please update the Wiki page accordingly?

**Comment by mythsunwind** [comment]
The Android .ttf is the recommended font for Linux. The github page states "Compatible with rooted Android devices and Linux". The .otf and .woff are only giving you black & white emojis and seem to be not as updated as the Android .ttf files.

I updated the link to the github repo on the page, because it was broken.

**Comment by nidico** [comment]
Great, thanks for explanation and for the clarification in the Wiki!
