### ISSUE TITLE
Offer option to disable internal update mechanism in preferences

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1015]
Wire Version: 2.15.2751
Wire for Web Version: 2017.10.09.0842
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

What is the expected result?
Wire should update when a user clicks "Update now" via the internal update notification which appears when a new version is available. Better still: Only offer this update notification/popover on an optional basis in order not to destabilize current video sessions. 

What happens instead?
Currently, the internal update mechanism doesn't work. CPU load increased to 98% making further video calls impossible. 

Proposed solution: 
Offer an option to disable the internal update mechnism for users who prefer updates through the repositories of a Linux-based distribution of choice rather than directly from Wire.

**Comment by gregor** [comment]
Thank you very much for your feature request. We have noted it down for future consideration when we revisit our update meachnism. That said: Linux does not have an update meachnism, which is why you should update to the latest release 2.17.xxxx. The update banner shown is just a reminder, that a new version of the webapp component being used is available. Nothing is installed in the backend when this banner shows. All a click on this link does is restart the app to trigger a fresh load of app.wire.com - just like a page refresh in a browser would do.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.

**Comment by baimafeima** [comment]
Thanks for the clarification. This is then, in fact, not just a feature request but an actual bug as I see it. The "Update Now" button doesn't work as intended under Linux and is confusing for potential and actual users.
