### ISSUE TITLE
Preference to automatically launch

### ISSUE THREAD

**Issue by mcg** [wireapp/wire-desktop#104]
It's possible to manually add Wire to auto-start, but it would be nice for the app to provide a preference to add this easily.

**Comment by Finnerale** [comment]
A minimized auto-start would be cool too :+1:

**Comment by ConorIA** [comment]
In the short-term, can you add the app to your startup applciations? I have Wire start automatically because it is included in my start-up programs, which I think is the easiest way to do it! Though a 'start minimized' option might be useful. 

As a bit of a case-study: Rambox is an app that does AutoLaunch via Electron. ([See](https://github.com/saenzramiro/rambox/search?utf8=%E2%9C%93&q=autolaunch&type=Code)). 
When I had the app installed, I thought it was really invaisive. I would disable the option, and remove it from my startup programs, but every time there was an update, the darn program would auto-launch again. This was my experience on Linux, but I didn't like it.

**Comment by mcg** [comment]
My experience is a "Start on login" pref that is usually not checked. Once checked it adds itself to startup applications. Start minimized is also nice option.

**Comment by ConorIA** [comment]
I've been working on the latter. :)

**Comment by shvchk** [comment]
For now I'm using [this script](https://gist.github.com/shvchk/e46ce47efb721f2cbeb6d170e6215bac) in autostart (on Linux) to start Wire minimized.

**Comment by Nateowami** [comment]
@shvchk Thanks! Is `--startup` an option specific to Wire, or is it an Electron thing? I don't see any documentation for it.

**Comment by ConorIA** [comment]
@Nateowami it is specific to Wire. By the way, auto launch is coming in the next release!
