### ISSUE TITLE
improve image upload speed (drag and drop)

### ISSUE THREAD

**Issue by ManthanoPoly** [wireapp/wire-desktop#1041]
**Wire Version:** 2.17.2808
**Wire for Web Version:** 2017.10.09.0842
**OS:** Win10 15063.674
Do you have an antivirus software installed: Windows default

What steps will reproduce the problem?
1. drag and drop image into Wire Desktop app

What is the expected result?
that the image shows up as instantly as in the Whatsapp Desktop app. The images I drag into the wire desktop app are 24Mpix large /~6MBytes.

What happens instead?
roughly a 5 second delay, other contributing factors 
**CPU:** Core i5 760 @2.80GHz (7y old)
**RAM:** 12GB
**GPU:** Nvidia GTX 1050

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by gregor** [comment]
@ManthanoPoly Thank you very much for your report. What's slow in this case is most likely not the actual image upload but the processing of the image. If you send an image it gets compressed before sending it. During this time you do not yet see anything in the conversation. We are aware of this limitation but have not yet been able to allocate the resources in order to improve the experience but showing some feedback of the process in the conversation.

If you do not want your image to be touched you can upload it as a file instead. Just click on the paperclip to start upload this way. This saves the image processing time but will cause more data to be sent over the network. So you might want to avoid that if you are on a metered connection.
