### ISSUE TITLE
wire-desktop no longer be able to run on centos/fedora

### ISSUE THREAD

**Issue by lfarkas** [wireapp/wire-desktop#1082]
IMHO it'd be nice to have a system requirements for wire-desktop since there're many distros with many different package sets. RHEL/CentOS/Fedora is among the biggest ones. Yes I know wire-desktop can be run with the AppImage but it's not updated or should have to do manually. On the other hand many people like to install rpm packages on an rpm based distro. Until now it was easy to use eg with conoria / wire-desktop repo: https://copr.fedorainfracloud.org/coprs/conoria/wire-desktop/. Unfortunately the Gruntfile was recently changed from CoffeeScript to ES6 Javascript which require nodejs version >= 8 which cause:
grunt --arch=x64 --target=rpm linux-other
no longer be able to build on any RHEL/CentOS/Fedora latest release. 

What's more the generated rpm has this requirements:
nodejs(abi8) >= 8.1
nodejs(v8-abi5) >= 5.8

Although it can be run!!! (if we install it with nodeps)
This means nodejs8 only required for build not for run. 

So what's my request:

- please keep it in this way ie. do NOT require nodejs8 for run wire-desktop
- please modify the build in a way that generated rpm do NOT requires the nodejs with which it was build but only what's really needed. eg on RHEL/CentOS-7.4 it was only:
   nodejs(abi6) >= 6.11
   nodejs(v8-abi5) >= 5.1

**Comment by ffflorian** [comment]
Hi @lfarkas, thanks for the request.
Since Node.js 8 is now [LTS](https://github.com/nodejs/Release#release-schedule) and most of our code is also using ES6 (which, by the way, was implemented 95 % in Node.js 6 already) we will unfortunately not revert the Gruntfile to ES5. Please install the latest Node.js version on your system or [babelify](https://babeljs.io/repl/) the file on your system before installing.
