### ISSUE TITLE
AppImageUpdate cannot update the wire AppImage

### ISSUE THREAD

**Issue by corppneq** [wireapp/wire-desktop#1083]
Operating system: cat /etc/os-release 
```
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

**What steps will reproduce the problem?**
1. `./AppImageUpdate-443.g69bf471-x86_64.AppImage wire-2.15.2751-x86_64.AppImage `

**What is the expected result?**
Update Works.

**What is the actual result?**
```
appimageupdate wire-2.15.2751-x86_64.AppImage      Cannot update this file
You need to an updater that can handle 
```

**Comment by TheAssassin** [comment]
There's two problems with this AppImage:

 * It is type 1. AppImageUpdate, as of now, cannot handle type 1 update information.
 * I can't see any update information in there anyway, and there's no `.zsync` files etc.

@corppneq with an up to date version of AppImageUpdate, you would've got a way more detailed description of what went wrong:

```
> wget https://github.com/wireapp/wire-desktop/releases/download/release%2F3.0.2816/wire-3.0.2816-x86_64.AppImage
> wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-c31f1dd-x86_64.AppImage
> chmod +x ./AppImageUpdate*.AppImage
> ./AppImageUpdate*.AppImage wire-3.0.2816-x86_64.AppImage
Checking for updates...
Type 1 AppImage update information is currently not supported!
Could not find update information in the AppImage. Please contact the author of the AppImage and ask him to embed update information.
Update check failed, exiting!
> ./AppImageUpdate*.AppImage wire-3.0.2816-x86_64.AppImage -d
Parsing file: wire-3.0.2816-x86_64.AppImage
AppImage type: 1
Raw update information: 
Update information type: Invalid (usually means that it couldn't be parsed)
```

So, here's what you should do:

 * Instead of using the _really_ out of date, deprecated AppImageAssistant, switch to appimagetool and produce a type 2 AppImage
 * Embed update information for your AppImage. The [specification](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases) defines a special syntax for GitHub releases. You could probably go with this string: `gh-releases-zsync|wireapp|wire-desktop|latest|wire-*x86_64.AppImage.zsync`. `latest` in there instructs AppImageUpdate to look for the latest release.
 * Produce a `.zsync` file that can be used for AppImageUpdate (appimagetool will do it for you as soon as some update information is specified). But make sure to upload them _as well_ to GitHub releases. Without them, the updater can't update your files.
 * Think about providing a alpha/beta update channel by uploading all your builds as pre-releases to GitHub releases. Most AppImage repositories use [uploadtool](https://github.com/probonopd/uploadtool) for this purpose. It creates a pre-release for every new successful build, always called the same (by default `continuous` but one can change it, check out https://github.com/Subsurface-divelog/subsurface/releases). By switching `latest` for `continuous`, those AppImages will then look for new `continuous` releases and update to them.

**Comment by corppneq** [comment]
@TheAssassin  According to AppImageUpdate, AppImageUpdate 443.g69bf471 is the most recent version

```
appimageupdate AppImageUpdate-443.g69bf471-x86_64.AppImage      /tmp/.mount_Kx7aJm/usr/bin/appimageupdate: Zeile 107: Warnung: command substitution: ignored null byte in input
Getting version information from Bintray
Latest version: 443.g69bf471
Read /home/pbeccard/.local/bin/AppImageUpdate-443.g69bf471-x86_64.AppImage. Target 100.0% complete.      
100 percent
Target AppImageUpdate-443.g69bf471-x86_64.AppImage
verifying download...checksum matches OK
GPG is not installed; hence skipping signature verification
used 393216 local, fetched 0
Successfully updated to version 443.g69bf471
```

**Comment by TheAssassin** [comment]
@corppneq I have no idea where you got that build from, but AppImageUpdate is **solely distributed** via GitHub releases. Please get it here: https://github.com/AppImage/AppImageUpdate/releases

**Comment by corppneq** [comment]
From:

- https://bintray.com/probono/AppImages/AppImageUpdate
- https://bintray.com/probono/AppImages/download_file?file_path=AppImageUpdate-443.g69bf471-x86_64.AppImage
@probonopd ping

**Comment by TheAssassin** [comment]
@corppneq I asked @probonopd to remove those binaries from Bintray. Sorry for the confusion.

**Comment by probonopd** [comment]
Done. Sorry for the confusion caused.
