### ISSUE TITLE
"Decrypting Messages" takes hours

### ISSUE THREAD

**Issue by highmeh** [wireapp/wire-desktop#1105]
Wire version: Version 3.1.2822
Wire for web version: 2017.11.10.1041
Operating system: Mac OS 10.12.6 (16G1036)
Which antivirus software do you have installed: N/A

What steps will reproduce the problem?
1. Leave Wire desktop closed for ~24 hours
2. Send a number of messages as per normal conversation through Wire mobile on the same account
3. Attempt to re-launch Wire desktop. 

What is the expected result?
Wire should launch, load new messages, decrypt messages, and open the client.

What is the actual result?
Wire launches, loads new messages in the background, and begins decryption. The following screen is visible for many hours, and persists through Wire restarts and reboots. Message decryption is extremely slow. User is unable to read old messages, message other contacts, or read any messages previously sent on mobile during this time. The Mobile client can continue as expected during this time.
<img width="754" alt="screen shot 2017-11-11 at 11 08 46 pm" src="https://user-images.githubusercontent.com/18130003/32696750-4ef838a4-c735-11e7-971d-d9b5f3011f1d.png">

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by hap124** [comment]
Same behavior on Ubuntu 16.04 with the dekstop app on multiple installs. Update today didn't change anything. I can use the webapp but the dekstop app just hangs on "decrypting" endlessly.

**Comment by manasb** [comment]
Seeing this issue as well on Fedora 25.

**Comment by randomdavis** [comment]
I am seeing this issue on Windows 10. A group conversation received thousands of new messages in it since I last opened the desktop app which I assume is the problem. Upon opening the app, it stayed on the Decrypting screen for over half an hour before finally finishing.

**Comment by hap124** [comment]
Hey Wire devs....this is a serious issue and has been open for 2 weeks now with not a peep. Tell me I am wrong but it feels like since Wire for Teams started you guys have let the rest flounder. There were several reassurance that the existing free features and apps would always be there and up to date but more and more bugs are occuring to the point a few of my hard earned converts have given up on Wire. What's going on?

**Comment by ffflorian** [comment]
Hi, thanks for flagging. We are currently investigating this bug but it's not trivial because it shows up only for some users. We hope to fix it soon, so please stay tuned.

**Comment by gregor** [comment]
@hap124 We are fully aware of the severity of this issue which is not only tracked here but also in #876 for example. We have spent a lot of time investigating the issue. What we see is that the decryption process is heavily throttled. The browser is not actually busy decrypting the whole time but there is a pause of a second or more after each individual message decryption. This is not something we can currently explain with the code. If you look at the list of developers you can see that we are a comparatively small team. Be assured that we are aware of the problem, that some of our users see, and are investigating possible solutions. This is definitely on the top of the list of things we need to improve - currently we just have not been able to explain the behavior we see and thus have no means of fixing it. We will continue to investigate and hope to solve this issue as soon as possible in order to address your concerns.

Additional "me too" posts have unfortunately not added any meaningful insights to the nature of the problem. We decided to expose the strings to better monitor the app start process next to the progress bar in order to have a better understanding of different issues people might see during app start and get a grip on those cases where decryption is painfully slow as described above.

**Comment by hap124** [comment]
@gregor I appreciate the response and didn't mean to sound ungrateful for your work...it's just so frustrating seeing people who were hard to get on the platform to begin with give up because of bugs and hassles like this, notification hang ups, delayed messages etc...all the things you see in issues here.  I sold Wire as "a better Skype with privacy" and 80% of the converts have since bailed. The non techies not wanting to deal with bugs ever, and the techies saying development feels stalled. There is no better option and I don't want to go back to garbage like Skype and WhatsApp just to talk to people. 

The other issue noted might be related, but in my case and those I talk to we use self destruction so there aren't thousands or even hundreds of messages in the history...a day's worth at most. If I can give you any logs tell me where and how to get them. I've not used the desktop app for weeks now and use the webapp as a workaround for now.

**Comment by Setitch** [comment]
Might be the chrome throtting invisible cards be a cause of this here?

**Comment by hap124** [comment]
So this is still an issue for me. I cannot get the desktop app on ubuntu 16.04 to load at all. It stays in the "decrypting messages" status endlessly and runs the CPU up as long as I leave it open. If there are some logs or some way to contribute to getting this solved please tell me how to retrieve and post them. I have used the webapp as a workaround and about half the time it hangs in the same state for 5-10 min before loading while loading promptly other times.

**Comment by hap124** [comment]
I give up. A month and a half...no communication or resolution but "we know about it". No response to offers of logs or info. My hard earned Wire contacts have bailed. It's a shame as I thought this was the app that would change things.

**Comment by gregor** [comment]
What's the size of your IndexedDB for accounts that load slow?

**Comment by robertnurnberg** [comment]
`> du -sh .config/Wire/IndexedDB/`
`5.5M    .config/Wire/IndexedDB/`

I had the bug a couple of days ago on a machine that I had not used for 3-4 weeks. Decrypting took hours, so that I eventually gave up. On the machine I use every day, decrypting only takes seconds.

**Comment by benjaminglass1** [comment]
This also occurs upon waking up from sleep mode in Windows 10. If any messages have been sent or received while the computer is in standby, each individual message takes over a minute (sequentially, one after the other) to be received by the client. Even 30 messages can up the time to over half an hour, especially if any of them involve media (GIFs, photos, etc.).

**Comment by Blackli0nXX** [comment]
@gregor If I could suggest two features that would end this problem: allow the user the option to open Wire without downloading previous messages, just like whenever the user first logs into Wire on a new device; alternatively or additionally allow the user to use the application while the new messages are still being loaded in, and just have the previous messages appear as they are loaded.

**Comment by zx2c4** [comment]
How's the port to wasm coming along?

**Comment by daniel-gallagher** [comment]
Just wanted to mention that I built wire-desktop from the current source and made sure to install libsodium-neon prior to doing so, as is instructed in the README. There is an exponential increase in speed with this setup. 1250 messages took only 3min 32sec to decrypt last night. 

This morning, I started the app built from source at the same time as the prod app on my Mac to see which would decrypt the overnight messages first. The app from source did it in 45 seconds, whereas the Mac was only halfway done 15 minutes in when I just decided to close it and uninstall to make the move over to the source code distribution. libsodium-neon seems to be a big step in the right direction!

**Comment by gregor** [comment]
@daniel-gallagher Unfortunately not. All our public production builds have been using libsodium-neon for quite some time.

**Comment by daniel-gallagher** [comment]
Interesting... well then something in the current source over the production build has had a significant increase in the app speed. I just built it again for MacOS and it is even faster than my Linux build.

**Comment by kurobeats** [comment]
I too am seeing the speed increase from libsodium-neon that @daniel-gallagher mentioned. I might stick with compiling myself.

**Comment by gregor** [comment]
The speed increase is most likely linked to the fact that you are running a fresh install with a fresh database. Do not be surprised if the self compiled build slows down over time as well. We are investigating and working on improvements.

**Comment by Viss** [comment]
+1 to @daniel-gallagher on this one. I was able to reproduce his steps to make my macos desktop app WAY WAY WAY faster.
decrypting 1700+ messages took something like 25 seconds. 
here's what I did to make that happen:

- clone down wire-desktop
- install rust, per instructions
- edit package.json
- edit line 25: change 'macos-prod' to 'macos', so the line reads: ' "build:macos": "grunt macos", '
- save package.json
- npm install
- wait a while
- npm start
- enjoy newer, faster wire desktop client

**Comment by zx2c4** [comment]
Nice to hear there's a way to speed up the desktop client.

However, for those of us who don't want an Electron backdoor (XSS ⇒ RCE), getting something like this in the web browser client would be quite nice, perhaps via WASM.

**Comment by Viss** [comment]
Yup.
But using the custom compiled desktop app will help pass the time til the web client behaves better.

**Comment by jack-cole** [comment]
Been having this issue for over a year. Happens on all 3 PCs I'm using. Happens on my girlfriend's PC, too. My IndexDB is 25.1MB in size. All my PCs and my girlfriend's have the same specs below.
**Wire version:** Version 3.0.2828
**Operating system:** Windows 10 (fully updated)
**Which antivirus software do you have installed:** Avira

**Comment by q2apro** [comment]
Same here. Such an awesome messenger, and then the web app takes ages to decrypt... :/

If I go in "private mode", I spare the decrypting, but also miss the chat history.

**Comment by jack-cole** [comment]
I set up a laptop with Wire recently, and the load times are near instant now. The difference is that the months of chat history are not on this laptop.  So that could be a big factor in why it takes so long.  Still takes forever on my PC. Both have Windows 10.

**Comment by manasb** [comment]
Still seeing this when trying to use the webapp. Very disappointing and frustrating.

**Comment by gregor** [comment]
We will bundle all feedback in a single issue. This will continue to be tracked in  #876
