### ISSUE TITLE
Windows XP support: exact problem with compiling / using

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-desktop#1114]
Please describe technically (as much details as possible) why Windows XP is not supported and minimal version is Windows 7? Please write exact details of problems with compiling/using. What "new" API used or something that does not exist in Windows XP. (Some is maybe emulated, some is maybe changed to old calls, etc).

It is better to add Windows XP support, just it is very "lightweight" OS.

**Comment by lipis** [comment]
Windows XP were released 16 years ago and the extended support for Windows XP by Microsoft ended on April 8, 2014 (3 years ago).. so if that's not enough to support something that old and not supported by their own maker these days, also since version 50 of Chrome, Google dropped supporting XP, two years after the official support of Windows XP has stopped. But due to some requirements and security issues that we need we support Chrome 56+ which is also impossible to run on XP. Last but not least Electron is supporting Win7+ and we are not planning to release a fully native app for each platform to make it "lightweight" for the "lightweight" - but outdated and not secure - OS.

So the main reason that we don't support it, is not that because Microsoft has stopped the security updates to it, but is because we really can't do much to support it if we want all the desired features that we have at the moment.
