### ISSUE TITLE
expired Timed messages vulnerable to being read. Still briefly readable when scrolling up.

### ISSUE THREAD

**Issue by jackj3000** [wireapp/wire-desktop#1120]
Wire version: Version 3.0.2816
Wire for Web Version 2017.11.10.1041
Operating system: Ubuntu Mate 16.04.3 LTS
Which antivirus software do you have installed: ClamAV

By simply scrolling up in the chat window, My old expired timed messages are still briefly readable in plain text for about 0.5 to 1 seconds, before they dissappear.

The expected result is that the expired messages cannot be seen in plain text simply by scrolling up. Not even briefly. 
This is a vulnerablity that allows someone to recreate expired message conversations by scrolling up while pressing screen cap or video capturing.

Thanks.

**Comment by dbquarrel** [comment]
I've reported this one as well. I don't think they care.

The problem seems to be that they're starting the message timer after you've read the message, but not considering the timers again when you move to read other conversations. Then, when you return to the conversation, all of the timers are considered then for message expiration. The result is you can visually watch the app run through the messages (slowly) deleting them (slowly). 

All of this is incorrectly implemented. I really wonder at the architecture of message expiration in this app as there are so many problems with it. Sometimes messages never expire at all and you have to kickstart them again by sending a 5 second expiration, then the app will run through and clean up all the failed-to-expire messages.

This kind of thing should be implemented on a priority queue with the next-available-to-expire message coming up. When that is popped, the priority queue will sort in the next-available-to-expire and this would be very efficient. It should be decoupled completely from the UI. No idea at all why the UI is involved in already read messages needing to be expired. 

Maybe someone has embedded data in the UI itself.

Regardless: the whole thing works very poorly at best, and incorrectly at worst (messages never expiring at all and users having to constantly set and reset timers). 

Wickr has this better implemented, with two sets of expirations: one being burn after reading, which is set after you've read the message, and the second an overall expiration timer. If the message is never read at all it will be expired. Also, with much finer granularity than wire's choice of time chunks less than 5 mins -or- 1 day and nothing else, as well as longer periods available. 

And it runs with 5% CPU instead of 40%. 

Wire is never going to fix these problems though according to what they just posted in another thread, they don't think it's important. All of the problems are tied together in the implementation of timers. It's been like this from day one, in spite of a lot of user complaints, their reaction is to brush it under the rug and implement bells and whistles for the marketing department. 

So get used to disappointment. This won't be fixed and this bug report is a duplicate of what I wrote here before and it will be also marked as "resolved" (Wire's "resolving" of a problem is "we're not going to fix it").

**Comment by gregor** [comment]
We are currently revisiting ephemeral messages and have completely reworked the way we track timers. While we are at it we addressed this issue. This will be part of the next release with is upcoming soon.
