### ISSUE TITLE
Main window black

### ISSUE THREAD

**Issue by CanuteTheGreat** [wireapp/wire-desktop#1218]
Wire version: Version Development
Wire for web version: 2017.12.20.1248
Operating system: Linux, Gentoo
Which antivirus software do you have installed: none

What steps will reproduce the problem?
1. git clone https://github.com/wireapp/wire-desktop.git
2. npm install
3. npm start

What is the expected result?
A normal-looking, working window.

What is the actual result?
The main window is black and no friends or messages or text is visible. Menu text is normal.

![wire-main](https://user-images.githubusercontent.com/12352246/35058724-b22faefe-fb6d-11e7-922e-2dee2534e342.png)

![wire-menu](https://user-images.githubusercontent.com/12352246/35058730-b62d9d2c-fb6d-11e7-8edb-b4cc37100eeb.png)

**Comment by gregor** [comment]
@CanuteTheGreat Every now and then we have to downgrade the electron version on the master branch to build a new Windows release. Due to a blocking issue in all version of electron above 1.6.x we need to do this. Linux and macOS release have long been on the 1.7.x branch of electron which is based on a newer version of Chromium that implements a IndexedDB version 2. If you have previously used a build with 1.7.x and then downgrade the browser storage is no longer compatible and you will see above behavior.

Building from master is not recommended due to issues like these. Not every commit can be garantueed to have release quality due to the multiple platforms that we target and the single branch approach we still have in this repository. Stick to the commits we tag as releases to be safe. Most of the new features are introduced via webapp updates anyway.
