### ISSUE TITLE
wire collecting location information

### ISSUE THREAD

**Issue by bulgin** [wireapp/wire-desktop#1281]
If a user clicks on "Devices" a series of encryption information is shown along with location information of the user and date time stamp of install - how is keeping that information anonymous?  It seems to me having the location information of the user present in the app is a serious privacy issue for an app that is designed to anonymize users.
![bal](https://user-images.githubusercontent.com/16614115/36282641-ccc63878-126f-11e8-9c57-3b0d506ffb64.jpg)
![bal](https://user-images.githubusercontent.com/16614115/36282652-d8b252fc-126f-11e8-93b4-f85504aef79a.jpg)

Wire version: 
Wire for web version: Version 3.0.2816
Operating system: Ubuntu 16.04
Which antivirus software do you have installed: rkhunter

What steps will reproduce the problem?
1.Click on devices
2.
3.

What is the expected result?
As expected

What is the actual result?
As expected.

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by ffflorian** [comment]
Hi @bulgin,
please see https://github.com/wireapp/wire-webapp/issues/361#issuecomment-293204652.

**Comment by cardassian-tailor** [comment]
@ffflorian  the original issue was closed - is there any indication that this behavior will change? Id prefer this be opt in, instead of opt out. However, since this occurs during account activation it would be hard to talk the user into providing their location details for future notification of possible brute force attempts. 

How about instead, during account registration, you do: 

1) account recovery codes
2) 2fa via u2f. 
3) anything other than collect location data on users. 

If and when this changes, what will occur with the location data you have already collected?

**Comment by gregor** [comment]
There are no changes planed. The location is based on your IP at the time of device creation as outline in our legal documentation and whitepapers which you can find on our website.
