### ISSUE TITLE
Number of group participants is off by one

### ISSUE THREAD

**Issue by fbruetting** [wireapp/wire-desktop#1341]
The group overview doesn’t count the user itself and thus shows a wrong number of people. Please count the user itself, or display something like “you and 666 other people”. Otherwise, this could be problematic if you for example do reservations, etc.

**Comment by Yorgos-V** [comment]
Hello @fbruetting,

thank you very much for your comment.
Since the beginning, Wire excluded yourself from any part of the UI. 
This is something that we have been changing slowly on other parts of the app and will revisit on this one. 
Thanks again for highlighting it on this specific screen and for your suggestions.
