### ISSUE TITLE
Doesn't render compound emoji correctly. Example: 🧘‍♂️

### ISSUE THREAD

**Issue by dwt** [wireapp/wire-desktop#1371]
Wire version: Version 3.1.2822
Wire for web version: Wire für Web Version 2018.03.12.1141
Operating system: Darwin crest.fritz.box 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Which antivirus software do you have installed: none

What steps will reproduce the problem?
1. Get a message with 🧘‍♂️
2. Look at it
3. Wonder about the strange rendering

What is the expected result?
🧘‍♂️

What is the actual result?
🧘‍♀️ ♂

Please provide any additional information below. Attach a screenshot if
possible.
![bildschirmfoto 2018-03-29 um 09 36 17](https://user-images.githubusercontent.com/57199/38076035-a60fc0c4-3334-11e8-92c8-5233b1b76c09.png)

**Comment by maximbaz** [comment]
It's a bug in Chromium (the engine behind Wire Desktop), or in fact a regression. I found this issue back [in July](https://github.com/emojione/emojione/issues/524#issuecomment-312722499), I confirmed that the issue was fixed [in November](https://github.com/emojione/emojione/pull/531#issuecomment-345757707), but now the issue is back again 😞 

Emojis look fine in Firefox.

-------

In fact, this is how your bug report looks in Chromium as of today:

> ![image](https://user-images.githubusercontent.com/1177900/38086939-8f2152ac-3356-11e8-99b3-5f7c5aea0fb0.png)

And this is how it looks in Firefox:

> ![image](https://user-images.githubusercontent.com/1177900/38086958-a4137d8e-3356-11e8-83c8-8c51507570a6.png)

**Comment by gregor** [comment]
@maximbaz Please keep in mind that our desktop apps are based on electron. These do not include the latest Chromium version at this point in time.. You can always see those version numbers at https://github.com/wireapp/wire-desktop/wiki/Builds

**Comment by gregor** [comment]
Hopefully we can soon ship desktop versions based on newer versions of electron. Our current internal builds are based on 1.8.7 as the 2.x branch still sees some compatibility issues. This will at least bring us Chrome 59.
