### ISSUE TITLE
Main content section has maximum width

### ISSUE THREAD

**Issue by Siguza** [wireapp/wire-desktop#1392]
Wire version: 3.1.2822
Wire for web version: 2018.04.09.1016
Operating system: macOS Sierra 10.12.6
Which antivirus software do you have installed: None

What steps will reproduce the problem?
1. Open Wire.
2. Make the window very wide (>1000px).
3. Open any conversation or settings page.

What is the expected result?
The main content section (like where messages appear) would grow to the right to fill up all empty space.

What is the actual result?
After ca. 800px, the content section stops expanding, leaving more than half my monitor blank in full-screen mode. This is especially infuriating with code blocks in messages, within which I then have to scroll sideways even though they would easily fit on my monitor if it wasn't for that weird width limit of the container.

**Comment by Yorgos-V** [comment]
Hello @Siguza,

Thank you for your comment.

The reason why the content stops at around 800px is because we want to keep the line length of the text between 75–85 characters per line. Various studies have shown that 45 – 75 characters per line are more pleasant for reading, whereas from 75–100 can be read or scanned faster. Text lines longer than 100 would affect readability.
You can also have a look [here](https://en.wikipedia.org/wiki/Line_length)

Once again, thank you for your comment.

**Comment by gregor** [comment]
This is a design decision that we aren't going to revise at this time. We will definitely consider your feedback moving forward.

**Comment by selurvedu** [comment]
FYI, Slack does not have this limit neither in their official desktop client nor in a web app. And that design decision does not break any UX. Although, I have not seen it in action on ultra-wide screens, that may really be inconvenient.
