### ISSUE TITLE
Push-to-talk feature does not exist

### ISSUE THREAD

**Issue by AlexFolland** [wireapp/wire-desktop#1511]
I want to be able to be silent unless I'm talking, so I can sniffle or sneeze without disrupting the conversation.  My breathing is a little messed up from a deviated septum, so it's loud when I'm not speaking.  This is critical for users with breathing problems.

As https://github.com/wireapp/wire-desktop/issues/1188 was erroneously closed and https://github.com/isaacs/github/issues/583 is still not fixed, this new issue must be opened because I can't reopen the original issue.

**Comment by gregor** [comment]
The other issue was not erroeously closed. As stated in our issue template we will not use the repository to keep track of feature requests. While we appreciate your feedback I am again going to close it. There are no plans on implemeting this feature into Wire.

**Comment by AlexFolland** [comment]
Where should I track it then?  It needs to be tracked.  I still disagree that it's just a normal feature request.  It's such a basic feature of any voice chat software that it seems like a bug to not have it, and it makes it impossible to recommend.

**Comment by gregor** [comment]
@AlexFolland Check our website. We are not a voice chat software. Wire is a secure collaboration platform focused first and foremost on business customers in order to generate the revenue that will allow us to continue to support a free cosumer product.

We have noted down your request. There is no public space to track it. I don't want to crush your hopes but this feature is very unlikely to find its way into our roadmap.

**Comment by AlexFolland** [comment]
You say "we" and "our", but if it's FOSS, what does one particular group have to do with it?  Anyone could implement it, in theory, right?  I could create a bounty and you'd get a nice pull request with the feature packaged and ready to be merged.  Am I wrong about that?

**Comment by gregor** [comment]
No. I work at Wire. While the consumer use is free our business offerings are SaaS. All of our code is open source so that it can easily be reviewed and the security audited. We only accept a certain set of contributions. Changes to the UX and new feature will not be accepted, which you can see in our contribution guidelines at https://github.com/wireapp/wire#contributing-to-the-code. Contributing PRs conflicting with these guidelines will be rejected
