### ISSUE TITLE
Man-in-the-middle attacks can be perfomed on Wire.com at anytime! 

### ISSUE THREAD

**Issue by Crypto-Anarchist** [wireapp/wire-desktop#1542]
I strongly suggest to urgently sign wire.com DNS with DNSSEC Algorithm 14 (ECDSA Curve P-384 with SHA-384)! 
This must be done soon as possible otherwise an attacker can **poison the DNS server** and inject a new IP for example for app.wire.com with a high TTL (Time To Live). This attack can be done in **10 seconds** if someone has experience like myself and this can be fatal for wire! 

If the attacker chooses to forward some traffic to the original IP than it will makes him effectively undetectable! However, such attack can't be done without obtaining a valid SSL certificate for the domain which is easy since wire has no **Certification Authority Authorization (CAA)** in the DNS. 

Regarding the SSL certificate and cipher suites used currently by Wire I must say that the engineers probably have no clue about security because far as I can tell wire in this very moment providing **imperfect forward secrecy**  and all pages are vulnerable to the **BEAST attack**. I suggest to immediately remove all ciphers which is not on ECDHE! ONLY USE Galois/Counter Mode (GCM) and remove Cipher Block Chaining (CBC)! 

In order to mitigate the BEAST attack disable TLSv1.0 and TLSv1.1! No one needs that today! 
I recommend also the switch to secp384r1 Elliptic Curve! 

In short: Sign DNS and include a CAA policy in it! Than mitigate the BEAST attack by removing old TLS versions and fix the imperfect forward secrecy by removing all CBC cipher suites and those which is not ECDHE! Finally fixing the Apache server which exposing the version number to the public! 

**Wire is not as secure as it's should be or how it's promoted! Who did the audits probably they are a bunch of capitalists who have no experience in security at all!**

I offering a very powerful security audit to wire and I accept only Bitcoin as payment. 
This recommendations above are for free!

**Comment by raphaelrobert** [comment]
Hi @Crypto-Anarchist,

Thanks for your report. It seems you looked at the naked domain (wire.com) which is neither part of the product directly nor this repository.

We apply different security rules for the website than for the actual product.

The Wire apps all use strict certificate public key pinning when connecting to the backend servers, a measure which is much stronger than DNSSEC or CAA records. The backend servers also use TLSv1.2 exclusively.

For the website we have to strike a balance between compatibility and security. Since the website doesn't host any user data as such, the security requirements are not the same, but we would still like to go for the best options.

We will soon disable TLSv1.0 and TLSv1.1 for the website soon, since now only very few browsers still require it.

But we can address your points more specifically:

> I strongly suggest to urgently sign wire.com DNS with DNSSEC Algorithm 14 (ECDSA Curve P-384 with SHA-384)! This must be done soon as possible otherwise an attacker can poison the DNS server and inject a new IP for example for app.wire.com with a high TTL (Time To Live). This attack can be done in 10 seconds if someone has experience like myself and this can be fatal for wire!

Unfortunately DNSSEC is not available on AWS. As soon as it becomes available we will enable it.

> If the attacker chooses to forward some traffic to the original IP than it will makes him effectively undetectable! However, such attack can't be done without obtaining a valid SSL certificate for the domain which is easy since wire has no Certification Authority Authorization (CAA) in the DNS.

CAA has been enabled recently.

> Regarding the SSL certificate and cipher suites used currently by Wire I must say that the engineers probably have no clue about security because far as I can tell wire in this very moment providing imperfect forward secrecy and all pages are vulnerable to the BEAST attack. I suggest to immediately remove all ciphers which is not on ECDHE! ONLY USE Galois/Counter Mode (GCM) and remove Cipher Block Chaining (CBC)!

Removing CBC is not a realistic option for a website these days.
BEAST will be addressed with the TLS protocol upgrade.
PFS is not an issue for the website, as no sensitive data is sent. There is nothing secret about the website. Again, this is for compatibility reasons, on modern browsers TLS connections with PFS will be used by default.

> In order to mitigate the BEAST attack disable TLSv1.0 and TLSv1.1! No one needs that today!
I recommend also the switch to secp384r1 Elliptic Curve!

As mentioned in the beginning, these versions of TLS will be decommissioned soon. Regarding the curve secp384r1, AWS only supports secp256r1, but the provided security level is not known to be weak (it is roughly equivalent to RSA 3072 bits). 

> In short: Sign DNS and include a CAA policy in it! Than mitigate the BEAST attack by removing old TLS versions and fix the imperfect forward secrecy by removing all CBC cipher suites and those which is not ECDHE! Finally fixing the Apache server which exposing the version number to the public!

The security benefit of hiding the Apache version is low. This would only be an issue if the version was vulnerable. We prefer transparency to ‘security through obscurity’.

> Wire is not as secure as it's should be or how it's promoted! Who did the audits probably they are a bunch of capitalists who have no experience in security at all!

We are always happy about reports. At Wire we encourage a polite and respectful tone of voice, which we would expect from anyone we work with.

**Comment by Crypto-Anarchist** [comment]
What a piece of shit you are!

**Comment by Crypto-Anarchist** [comment]
LOL. Amazo AWS far as I know is in the United States. Sound like you guys are fucking liars.
