### ISSUE TITLE
--portable flag doesn't work in new wire version in linux

### ISSUE THREAD

**Issue by k9iaw3** [wireapp/wire-desktop#1554]
version: wire-3.2.2840-x86_64
file: wire-3.2.2840-x86_64.AppImage

throws an error...

A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: path is not defined

**Comment by gregor** [comment]
Sorry for the oversight. We are fixing this on master now but it might take some time for another prod build.

**Comment by jomandas** [comment]
@gregor hi. is there temporary work around for this issue like adding a path argument to the run command?
i tried for example to navigate to the app file before running and that didnt work.
i could run it without --portable but now each time i run wire it doesnt recognise i am running from the same device and therefore i dont get message history. any ideas?
also how long does it take for next release? can this be fixed in an rc build before a main release?

**Comment by gregor** [comment]
The fix for this issue was part of the release that was published today.
