### ISSUE TITLE
Flatpak package support

### ISSUE THREAD

**Issue by schewara** [wireapp/wire-desktop#1586]
As AppImage does not (really) support updates and upgrading to a newer version is always very painful, it would be great to also provide a [Flatpak](https://flatpak.org/) Version for installation under Linux

If then also published on [Flathub](https://flathub.org/home), this would make the installation and updates very frictionless for endusers, as it is seamlessly integrates into the gnome-software application and picks up any updates automatically.

**Comment by gregor** [comment]
Thanks for your suggestion. But at this time we do not plan to add more Linux versions. I will go ahead and close this as a feature request.

**Comment by x80486** [comment]
So @gregor, there is a [Flatpak package](https://github.com/flathub/com.wire.WireDesktop/) already published in Flathub since `Sep 27, 2018`. It doesn't have any issues so far...so would you folks like to take over the maintenance of the same? It's always better if upstream developers (you folks) maintain those, whenever possible.

I'm asking because I'm the **principal maintainer** for it, but I was wondering if it's time for you folks to consider that release path along (or even instead of) the AppImage. If not, no problems, I'll keep maintain it until somebody wants to, and even so, I'll be "secondary maintainer" (if that's a thing) 😉

**cc./** @ffflorian 👆

**Comment by gregor** [comment]
@x80486 I am no longer working with Wire. Cannot be of any help with this issue.
