### ISSUE TITLE
Wire on linux not in PATH

### ISSUE THREAD

**Issue by sonicou** [wireapp/wire-desktop#160]
On Debian Linux (using the deb packages) the Wire binary is located in /opt/Wire/wire.
Although some desktop environments add it to the list of available desktop applications to be selected in menus, Wire is not found on the terminal since it is not in any of the PATH directorys. "which" does not find wire.
That breaks many use cases in which applications are started by command name and not the menu.

Please change the packaging so that the wire binary is located in the proper path, like /usr/bin or add a symbolic link

**Comment by ConorIA** [comment]
@lipis, the binary itself can't live at /usr/bin because it doesn't know where to look for the shared libraries it needs. The practical solution is to include a symbolic link. Not sure if this is something that needs to change on the electron-builder side. In my PKGBUILDs I link /usr/bin/wire to /usr/lib/wire/wire.

**Comment by lipis** [comment]
I would say on electron-builder side.. as it's has to do with the installation

**Comment by ConorIA** [comment]
:tada: Found it! https://github.com/electron-userland/electron-builder/issues/795
And the example: https://github.com/electron-userland/electron-builder/blob/master/templates/linux/after-install.tpl
