### ISSUE TITLE
Delayed ringing stop when using multiple devices

### ISSUE THREAD

**Issue by isj4** [wireapp/wire-desktop#1766]
Wire version: Version 3.0.2816
Wire for web version: Wire for Web Version 2018.09.28.1146
Operating system: Linux/OpenSuse LEAP15.0 + OpenSuse 13.1

What steps will reproduce the problem?

1: I have wire-desktop running on both devices, logged in as the same user.
2: Someone calls me
3: Both devices start ringing (good)
4: I answer the call on one device.
5: Other device keeps ringing for some seconds (duration varies)
6: It _seems_ that a voice connection is first being established on the first device  when the second devices has stopped ringing.

Expected result:
1: That the second device stops ringing almost immediately
2: The voice connection starts establishing immediately when clicking ok/answer

Actual result:
1: Second device keeps ringing for some seconds. Duration varies. A small delay would be expected (a few times round the Earth at lightspeed), but not several seconds.
2: The voice connection establishment _seems_ to be delayed until the second device stops ringing.

The two callee-devices are on same internet connection (lightly loaded)
The caller-device is in Calif, US.

**Comment by gregor** [comment]
Thanks for the report. Whether the call stops to ring when you accept it on another device currently depends on the type of device that you are accepting the call on. If this is a web based client (webapp or desktop application), it should and will stop ringing. If not that is a bug. If you accept the call on a mobile device, it will currently not stop rining. The mobile calling implementation does not include that feature as of now.

Is this within a group call? Then the delay stems from the heavy encryption of calling related events that need to be sent in order to connect the call.

Which device did you accept the call on? What kind of delay are we talking about? Is this a group? How many participants does the group have?

**Comment by isj4** [comment]
Both of my devices are running wire-desktop.
It is not a group call. It is a simple person-to-person call.
The ringing delay is noticeable - approximately 2-3 seconds.
The call-setup delay is also noticeable - usually at least 2 seconds.
I will try to conduct a test where I only have one wire instance running.

**Comment by isj4** [comment]
I have not been able to reproduce the behaviour. It _might_ have been caused the other party using a smartphone in a really location (basement), and that caused some of the signalling to be delayed. If I encounter it again I will reopen this case.

**Comment by fortran77** [comment]
I have encountered this phenomenon many times during the last 2–3 years, but not within the last few weeks. The symptoms are that a smartphone and a tablet (on the same Wi-Fi network) both ring. When I answer on one, the other continues to ring for quite a while, i.e., 10 seconds or more, before ceasing to ring.

While the second device is ringing (after I have answered the call on the first device), there seems to be no way of silencing the ringing on the second device while keeping the call active on the first device. The mute button on the second device does not silence the ringing. The hangup button on the second device silences the ringing and hangs up the call. If there were some way of silencing the ringing on the second device without hanging up the call, that would be a useful workaround.

**Comment by isj4** [comment]
Ok, so it isn't just my imagination. Re-opening case.

**Comment by fortran77** [comment]
Since my comment was for two mobile devices, maybe it doesn't indicate a bug. As Contributor gregor wrote, “If you accept the call on a mobile device, it will currently not stop [ringing]. The mobile calling implementation does not include that feature as of now.”

My real point was that it would be useful to have a method for silencing the ringing.

**Comment by ffflorian** [comment]
This should be fixed by now. Can you test if this problem still appears for you @isj4?
