### ISSUE TITLE
Native qt application for Linux-based operating systems (plus added benefit of extending to Haiku)

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#1795]
We all know that Wire in its current state is very heavy on resources. In fact, it uses more than my entire desktop environment, slowing down my computing experience especially on older laptops. I would greatly appreciate the efforts of a rewrite in a native application framework such as `qt` for Linux-based operating systems. Many thanks. 

This would also solve #1777 as `qt` applications can easily be ported to `Haiku` and you would immediately gain access to the entire Haiku user base and thus be the **only** privacy-focused instant messenger available on all major platforms. You came to market later than, let's say Threema, but one way to fix that is a universal platform strategy.

**Comment by ffflorian** [comment]
Hi @baimafeima, thank you for the suggestion. Sorry to give you a negative answer again but for now we don't have any plans for developing a native qt app.

**Comment by lipis** [comment]
We had this discussion in the past.. It's not a small effort, read #994 for more details.

**Comment by baimafeima** [comment]
@lipis Thanks for referring me to #994 and I greatly appreciate the efforts done by @ddobrev
Is it possible to close this thread in favour of #994, that is re-open the latter to allow for a more constructive discussion on this matter? By closing the previous thread you essentially stifled a very fruitful discussion of people getting togther to improve Wire in their free-time. I'd typically expect that open source also corresponds to a more open-minded and encouraging attitude.

**Comment by lipis** [comment]
@baimafeima Well since we are not planning to officially rewrite in QT there is no point of having this issue open. I was pointing you to that link, so you would realise that is not the simplest thing to do and you can't just do it in your free time. It's not [just a wrapper for the WebView](https://github.com/wireapp/wire-desktop/issues/994#issuecomment-334140683). Proof of concept and having a polished product for all platforms is two different things.

Having said that, the community is free to improve Wire in their free time, but we can't support the community with re-writting the desktop app.
