### ISSUE TITLE
Need help figuring out initial state loading (in Flatpak) when application is started again after closed

### ISSUE THREAD

**Issue by x80486** [wireapp/wire-desktop#1821]
Folks, is it possible you can help me figuring this one out: flathub/com.wire.WireDesktop/issues/1?

Basically, by following these steps (after installing the Flatpak) will let you replicate the issue:

- Start application (for the very first time)
- Log in successfully (and do whatever you want...or not)
- Close the application – without logging out/off
- Start the application again

The user should be logged in and the application state should be correctly loaded, but right now the startup process is aborted at some point. The user looks like it's logged in since you can see the icon (in the left pane), but nothing happens. In order to use the application again, you have to right-click on the user's icon and log out.

I'm asking for help because I can't see what Wire is doing at that stage, so I wonder if you have any insight on that part of the process.

Thanks in advance!

**Comment by x80486** [comment]
I do not believe this is an issue with Wire itself. I see the behavior with other (Electron-based) Flatpak applications as well (Slack, Atom, etc.), although the startup process is not affected as it currently happens with Wire.

**Comment by x80486** [comment]
Hey @ffflorian, would you mind taking a look at this one whenever you have some time? Maybe you have some valuable input that I may be missing. The thread on the Flatpak repository explains the situation really well. You would only need to install the Flatpak on a Linux box: `flatpak install flathub com.wire.WireDesktop` and run it as `flatpak run com.wire.WireDesktop` – if you would like to see more info, you can attach these settings `--inspect --devtools --enable-logging` right after the `run` command, in the end.

**Comment by x80486** [comment]
Hi @ffflorian, the current Flatpak (hosted in Flathub) was built from Linux release `3.3.2872`.

The way it works is we use the `.deb` files (for the specified architecture) and make the corresponding Flatpak.

Are there any changes in `Wire` related to the application life-cycle (start/close) from that release until now? If so, maybe on the next release this issue might go away. In any case, I'll give it another try from sources in the next hours – the last version I tried was `3.2.2840`.

---

The reason I couldn't built it from sources was because there are some limitations in the way the Flatpak does it nowadays. For Electron applications, the build must happens offline, and for some reason the `winston` and `node-addressbook` always fail to download. I guess it's because they are referenced by links instead of a normal `npm` dependency – I'm not sure, but in any case, that's a thing from the way the Flatpak is built, not this issue.

**Comment by ffflorian** [comment]
> Are there any changes in Wire related to the application life-cycle (start/close) from that release until now? 

We upgraded Electron from 1.8.8 to 3.0.10 so this could change a lot. We will release a new Wrapper version soon, so you might just wait until the new Linux build is released. :slightly_smiling_face:  

Unfortunately we don't have the time right now to figure out what's exactly going wrong with flatpak but we appreciate that you are digging into that. :+1: Let's see how it goes with the new release.

**Comment by x80486** [comment]
All right! Let's wait for the next wrapper version then! Thanks for the info :smile:

**Comment by x80486** [comment]
Hi @ffflorian, sorry to keep poking you on this one :innocent: ...but I updated the Flatpak manifest to `Linux 3.4.2879`, and I still see the same behavior.

This is the log stream from my console. I execute the application:

```shell
$ flatpak run com.wire.WireDesktop --inspect --devtools --enable-logging
Gtk-Message: 06:26:12.565: Failed to load module "pk-gtk-module"
Gtk-Message: 06:26:12.565: Failed to load module "canberra-gtk-module"
Gtk-Message: 06:26:12.566: Failed to load module "pk-gtk-module"
Gtk-Message: 06:26:12.566: Failed to load module "canberra-gtk-module"
Debugger listening on ws://127.0.0.1:9229/cc1fa161-c52f-416e-bcff-761ae617b1af
For help, see: https://nodejs.org/en/docs/inspector
[2:1126/062613.042071:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /usr/var/run/dbus/system_bus_socket: No such file or directory
   wire-desktop::main.ts [2018-11-26 06:26:13] Failed to read log directory with error: ENOENT: no such file or directory, scandir '/home/machina/.var/app/com.wire.WireDesktop/config/Wire/logs'
[2:1126/062613.085727:ERROR:browser_main_loop.cc(341)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2:1126/062613.103799:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
[2:1126/062613.115916:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
[2:1126/062613.269119:VERBOSE1:CONSOLE(7847)] "Main._createAppUI: 14.528076171875ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[2:1126/062613.280399:VERBOSE1:CONSOLE(7847)] "Main._showAppUI: 9.625ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[2:1126/062613.291664:VERBOSE1:CONSOLE(7847)] "Main._initializeTarget: 7.72998046875ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[2:1126/062613.413001:VERBOSE1:CONSOLE(7847)] "Main._lateInitialization: 0.56103515625ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[2:1126/062615.773378:WARNING:quota_manager.cc(1632)] No storage quota provided in QuotaSettings.
[2:1126/062739.137316:WARNING:audio_sync_reader.cc(175)] ASR: No room in socket buffer.: Broken pipe (32)
[2:1126/062739.238286:WARNING:audio_sync_reader.cc(175)] ASR: No room in socket buffer.: Broken pipe (32)
[2:1126/062739.379511:WARNING:audio_sync_reader.cc(175)] ASR: No room in socket buffer.: Broken pipe (32)
```

...then I close the application by using the <kbd>Ctrl + Q</kbd> combination – or alternatively the menu option `Wire | Quit Wire`; then if executed again, everything is fine:

```shell
$ flatpak run com.wire.WireDesktop --inspect --devtools --enable-logging
Gtk-Message: 06:28:08.221: Failed to load module "pk-gtk-module"
Gtk-Message: 06:28:08.221: Failed to load module "canberra-gtk-module"
Gtk-Message: 06:28:08.222: Failed to load module "pk-gtk-module"
Gtk-Message: 06:28:08.222: Failed to load module "canberra-gtk-module"
Debugger listening on ws://127.0.0.1:9229/85f88196-9e87-41e2-af26-94438f8a1b6d
For help, see: https://nodejs.org/en/docs/inspector
[2:1126/062808.408734:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /usr/var/run/dbus/system_bus_socket: No such file or directory
[2:1126/062808.425893:ERROR:browser_main_loop.cc(341)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[2:1126/062808.441798:ERROR:service_manager_context.cc(258)] Attempting to run unsupported native service: /app/Wire/content_gpu.service
[2:1126/062808.443714:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
[2:1126/062808.451994:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
[2:1126/062808.608349:VERBOSE1:CONSOLE(7847)] "Main._createAppUI: 15.006103515625ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[2:1126/062808.618460:VERBOSE1:CONSOLE(7847)] "Main._showAppUI: 8.382080078125ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[2:1126/062808.632299:VERBOSE1:CONSOLE(7847)] "Main._initializeTarget: 8.295166015625ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[2:1126/062808.733493:VERBOSE1:CONSOLE(7847)] "Main._lateInitialization: 0.584228515625ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[2:1126/062811.230439:WARNING:quota_manager.cc(1632)] No storage quota provided in QuotaSettings.
   wire-desktop::main.ts [2018-11-26 06:28:18] Closing window...
```

...but if I close the application using/clicking on the window's <kbd>X</kbd> icon (doom happens) and the application stays forever in a limbo state – after that event: `wire-desktop::main.ts [2018-11-26 06:28:18] Closing window...`.

As you can see, I never got my prompt back:

![screenshot from 2018-11-26 06-29-43](https://user-images.githubusercontent.com/34633617/49012487-8d46ce80-f147-11e8-8491-de205217c302.png)

---

All that "chatty conversation" is when I use all those settings on the command-line. If I use the desktop icon, the behavior is similar, but the application, once executed again, can never load the previous state; asks for login again and again...and then always fails in that operation. Looks like it's because it recognizes that there is still another instance running.

**Comment by ffflorian** [comment]
Hi @x80486,
thanks for the detailed report! :slightly_smiling_face: 

> but the application, once executed again, can never load the previous state; asks for login again and again...and then always fails in that operation. Looks like it's because it recognizes that there is still another instance running.

Yeah we have some checks for single instances, but I don't know how this interferes with Flatpaks.

I remember that @mythsunwind knows some more about the mysteries happening when a user clicks on the <kbd>x</kbd> icon.

**Comment by mythsunwind** [comment]
This is an ongoing topic since gnome project decided to remove the system tray area with gnome-shell >=3.26 (Fedora 28 seems to use gnome-shell 3.28).

When you use the <kbd>x</kbd> button of the window the application is not closed but the window is just hidden since the first release of wire-desktop. With a click on the tray icon the application window was shown again. To close it fully you have to use one of the other two ways (keyboard shortcut or `Wire | Quit Wire`)

When gnome project removed the tray area, we actually had a pull request to close the window on pressing the <kbd>x</kbd> button: https://github.com/wireapp/wire-desktop/pull/970

We hesitated to include the pull request because various different other desktop environments still supported the tray area AND people using a legacy version of gnome-shell (Debian Stable) would have experienced a drastic change in behavior. Additionally, while having some good arguments to remove the tray area (https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines) unfortunately gnome project did not provide a solution to deal with this removal on messaging application (Only examples for music players and cloud providers).

Meanwhile the reaction of the community to the removal of the tray area in gnome-shell was that Ubuntu created a gnome-extension (https://extensions.gnome.org/extension/615/appindicator-support/) based on https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators and everyone is now using it. We closed the pull request without including the code to close on <kbd>x</kbd>.

IMHO the correct way how to deal with it is to create a check like this:
* if appindicators are supported: hide window
* if appindicators are not supported: close application

Unfortunately I couldn't find the correct way how to check for appindicators support, most of the app to a check against XDG_CURRENT_DESKTOP which I find flawed because it is not very reliable (user might have older/newer versions of gnome-shell installed).

**Comment by mythsunwind** [comment]
After further investigation I need to correct my check, because it is possible to have a desktop environment that supports GTK legacy tray but not the Ubuntu's appindicators:
* if appindicators are supported: hide window
* if GTK legacy tray is supported: hide window
* if none of both is supported: close application

To check for appindicator support, it is possible to check dbus for a name org.kde.StatusNotifierWatcher described here: https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines

This can be checked by following command:
`gdbus introspect --session --dest org.kde.StatusNotifierWatcher --object-path /org/kde/StatusNotifierWatcher --recurse`
If the Ubuntu gnome-extension is installed this returns:
```
node /org/kde/StatusNotifierWatcher {
};
```
if not, it returns an error.

It might be possible to use a package called "dbus" for this: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/638/files

To check for GTK legacy tray support, I found the following example in C: https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines/TraySupportCheck

The xlib methods XGetSelectionOwner and gdk_x11_get_xatom_by_name_for_display may be accessed through an npm package "x11". Examples:
https://github.com/sidorares/node-x11/blob/4bddee6d5e83791920ce0934a8b6718d8c672bab/test/client-message.js#L17
https://github.com/sidorares/node-x11/blob/174cff9a9cdfff527ff03f799fd1e07c017190b0/examples/smoketest/selections.js#L8

The above ideas might work but need some implementation afford.

**Comment by x80486** [comment]
@mythsunwind, thanks for all this info! This is great stuff!

Now, @ffflorian, is this something you can improve on your end? Even if it's in the (hopefully not so far) future?

I guess I would also need to make some changes on my end in order to talk to `org.kde.StatusNotifierWatcher` (and what not), but that's a very minor change compared to all what's on that research from Sven.

**Comment by fbruetting** [comment]
I don’t understand why you break UX for the majority (Gnome users without the required tray/appindicator shell extensions), just for keeping a weird behavior (i.e. “closing doesn’t close”) for some minority people. In every other application, clicking the `X` is exactly the same as pressing `Ctrl + Q` or quitting via the menu – everything else is **unexpected**. And those applications which act differently, either ask the user or provide an option for daemon-mode in the settings.

And I **really** don’t think that closing an application after clicking the `X` is a “dramatic change in behavior”, as minimizing does lead to the same result while having the added benefits, that users
* are aware of background applications, and
* still are able to close that background application. (How dare they?)

Where is the dramatic impact for Debian Stable users?

I also don’t understand how daemon mode should be better than a minimized application window? Where is the benefit in hiding the presence of a running Wire instance from the user?

And why do you assume that people want to run Wire in the background, just based on if they are able to show tray icons / appindicators or not? I for example can see both icons – yet I still don’t like applications faking their non-existence.

Can’t you just provide a sane setting for that, like every other application does? Default there should certainly be no-daemon-mode. Users then would be able to opt-in (instead of opt-out) on weird behavior if they like (and understand!). Lollypop for example does this nicely.
