### ISSUE TITLE
Install updates without version in separate folder

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-desktop#2975]
Current wire desktop application install every updates in new folder similar 3.9.29.28, 3.10.31.38 etc. Just that is not a issue at all for basic users However extremely annoying task for people who use policy based(rule based) software firewalls. ex: windows, comodo, symantec, eset etc

I expect no one will comment below for ignore implement this request by mentioning wire application based on electron or any other reasons.

**Comment by ffflorian** [comment]
Hi @ArchiveBase, to keep things simple, we are using Squirrel to install Wire on Windows but unfortunately, choosing your installation directory [is not supported by Squirrel](https://github.com/Squirrel/Squirrel.Windows/issues/696). Maybe it's possible to set up your firewall so that all exectuables from the Wire installation dir are allowed to access the internet?

> I expect no one will comment below for ignore implement this request by mentioning wire application based on electron or any other reasons.

If you have a better solution, let us know :wink:

**Comment by ArchiveBase** [comment]
Hello @ffflorian 
> choosing your installation directory is not supported by Squirrel

The developer too aggressive however it seems looking new maintainer for that project

Something like this? https://github.com/ramboxapp/community-edition here with UI https://github.com/ramboxapp/community-edition/issues/1926 (likely it's near months versions auto update has issue but you can see resources used or v0.6.1 update work as well)

> Maybe it's possible to set up your firewall so that all exectuables from the Wire installation dir are allowed to access the internet?

It's not possible to set folder/dir on above mentioned most software firewalls. 😊

**Comment by ffflorian** [comment]
Thanks for the suggestions, I'll look into it!

**Comment by NetE1** [comment]
@ffflorian Any update about this?
I see this's not that difficult as you guys late, probably no priority
