### ISSUE TITLE
Improve screen sharing

### ISSUE THREAD

**Issue by ElucGeek** [wireapp/wire-desktop#304]
Could you improve the screen sharing to offer more functionlity than competitor, like:
- set someone as presenter in multi-user conference (creator of the conference can give moderator right and presenter right to other)
- Point something on the shared screen (a cursor with the name of the viewer will appear for x sec).
- Doodle on the screen while sharing (by the presenter) and while shared (by other)
- Give control to someone else on the shared screen

What do you think ? are some of them in the plan ?

In addition, any work in progress into screen sharing on mobile (see shared screen from a desktop and/or share the screen of a mobile)?

**Comment by helenakos** [comment]
@ElucGeek Thanks for the feedback. We don't have any immediate plans to implement this, however we want to hear your feedback and have design and product teams think about improvements. I will pass it on to the team. 

No work in progress for screen sharing on mobile at the moment.

**Comment by DOFfactory** [comment]
I would also appreciate the delegation of control, it will have a huge effect on attracting more users IMHO

**Comment by Talon24** [comment]
Hello! It would be great if the presenter could start/stop to share the desktop audio additional to VoIP (minus the audio coming from Wire itself).

**Comment by gregor** [comment]
Thanks you very much again for your request. While we see many way on how to improve our screen sharing implemenation, there is no immediate plans for changes to the product in this area.

Due to the nature of this being a feature request, I am closing this issue. We will continue to track and evaludate this internally as we want to focus on keeping the public issues as a bug tracker.
