### ISSUE TITLE
Enable configurable notification sound to address ease-of-use needs

### ISSUE THREAD

**Issue by JPUnix** [wireapp/wire-desktop#340]
Would it be possible to make the notification sound in Wire-Desktop either louder on longer or both? The single "dit" sound is too short and soft for some people to hear. A longer tone or bell would be nice.

**Comment by helenakos** [comment]
@JPUnix Thanks for the feedback. We cannot commit to changing it, so far we haven't received any complaints on the notification sound.

**Comment by JPUnix** [comment]
So what exactly is the threshold of reports will you need from hearing-impaired people will you need before you will address this issue? 10? 50? 100? 1000? I'm a hearing-impaired person that deals with other hearing-impaired people on a daily basis.  All of us agree that the notifications on the desktop version are essentially inaudible. Shall I get them to post here so that you may be inclined to add the ability to specify  notification sound from the Windows sound library? Please advise!

**Comment by cajuntechie** [comment]
While I am not hearing impaired, I agree that this should be configurable. If you are not near the computer when someone messages you, chances are you will not hear it. I've taken to pinging people immediately after sending a message just to make sure they know I've messaged. Please consider this yet another voice in support of configurable notification.

**Comment by gregor** [comment]
@JPUnix Thank you very much for your report.

Wire could certainly do a better job in offering ease-of-use adjustments in the areas of audible feedback and visual appearance. These can and should be added as optional adjustments to the existing user experience though. Your inital request did not indicate that need for medical reasons at all and was misinterpreted as such. Just making it louder or longer will leave many users unhappy as well, which you saw by the immediate downvote of another Wire advocate.. There is not right setting for all of us.

If you look at the list of open issues both here and on the webapp, which is an intergral part of the Wire apps for desktops, you can see that we have a lot of work to do and it is not always easy to prioritize.

I am sorry to say, butease-of-use features currently are not at the top of this priority list. This does not mean that they are not important to us but we have a limited set of resources and issues in the pipeline that affect many more users. There is no threshold for priorities to change but being reminded of the importance of ease-of-use features and votes on an issue like this certainly helps. I will have to ask for your patience though as this will not be addressed in the near future. Sorry to say.

**Comment by Simplenuity** [comment]
Hi Gregor,

Thanks for all the effort and your detailed explanation.

In this case I dare to disagree with you.
Not being able to hear a notification, which is there/implemented for a very good reason in the first place, renders the app to be useless, at least for certain setup/ use cases/ users!

I fully agree that there is no one-size-fits-all solution. So, adjusting it in a fixed way to hearing impaired people is definitely not the solution. It needs to be adjustable. The oldest telephone I can remember had the notification sound adjustable! It's a necessity to be able to use it. This has nothing to do with ease-of-use! BTW, you have chosen this category - and sorry, it's the wrong one. I doubt, that JPUnix would categories it like that. Even I - not being hearing impaired - don't.

Many requests on here fall into the category of ease-of-use. And even if they fall "only" it to that category, the one or the other will be the top-or-flop criteria for people using Wire or not. The huge competition in the messenger app market allows people to be that picky.

I do my best in promoting and convincing people to use Wire despite these ease-of-use issues, always in the hope they will get addressed down the line by adjustable settings. Not everyone is as passionate about Wire like I am and not everybody has an Android device available so that they (can) do what I do as a workaround for this "bug". As the Android app allows the notification sound to be adjusted I solely use it for just that, getting the notifications - to then move over to my desktop app to communicate.

I do understand that there are many issues out there that need addressing. And I appreciate they are damn hard to prioritize. If you/the team still think this issue is way down the list before getting fixed by adjustable settings, what about at least a better compromise for the time being, using a different, bit louder notification sound? Any app with notification sound comes with a default sound and volume, that's somewhere in the middle, covering lots of use cases. The "click" of Wire is at the far end of low volume to the point you could just turn it off completely. It would be an interim solution to increase the volume at least a bit, use a slightly louder sound.

Thanks for your consideration.
Keep up the great work!

**Comment by gregor** [comment]
There are many valid scenrios where configurable sounds would be helpful. At this time an improvement like this is not on our immediate roadmap. We want to focus on tracking bugs in the public issue tracker. I will go ahead and close this requests. We will continue to track and evaluate it for our roadmap.
