### ISSUE TITLE
Implement Local Muting

### ISSUE THREAD

**Issue by Deathsbreed** [wireapp/wire-desktop#356]
I've been using Wire for a while now, and one of the issues some friends and I have come across while using Wire are that in group calls we can't mute an individual that's in the call without simply recalling without that person.

Example where this is useful: someone in the group chat goes afk but doesn't mute himself, now we're all stuck listening to whatever is going on in his house and his grandfather playing the piano when we're trying to play a game, but we can't mute him (so I ended up kicking him from the group temporarily, but that's not a long-term solution).

If this feature does already exist then I suggest it be more visible, as I have seen that a lot of the features and UI in Wire (at least the desktop version) is quite hidden.

Thanks!

**Comment by helenakos** [comment]
Indeed a very useful feature thank you! Noting it down.

**Comment by tmikaeld** [comment]
Discord have a volume slider "per user in a group" that is extremely useful since the input volume varies a lot between microphones and soundcards, Wire should add the same.

**Comment by gregor** [comment]
Thanks again for your feature request. I will go ahead and close it at this time. We have no immediate plans to implement this feature but will consider it whenever we lay our roadmap. Due to the nature of this being a feature request, we will only track it internally as we want to move forward with some housekeeping on the public issues in order to better serve as an bug issue tracker.
