### ISSUE TITLE
Allow even smaller window size

### ISSUE THREAD

**Issue by ciastek** [wireapp/wire-desktop#381]
Thanks to #123 minimum window size is now 760x512.
I'd love Wire to allow even smaller window, to fit nicely next to the e-mail client.

Telegram's default layout is similar to Wire's:
![screen_shot_2017-01-30_at_06_29_06](https://cloud.githubusercontent.com/assets/637051/22413517/ebf202a6-e6b8-11e6-88c5-754e63f5e4ff.jpg)
On width 650px and below it switches to mobile-like layout:
![screen_shot_2017-01-30_at_06_29_17](https://cloud.githubusercontent.com/assets/637051/22413545/275ee502-e6b9-11e6-8368-e954a17eeac4.jpg)
![screen_shot_2017-01-30_at_06_29_21](https://cloud.githubusercontent.com/assets/637051/22413547/2cf30764-e6b9-11e6-8d03-cd31970ca369.jpg)
BTW: Telegram's minimum window size is 380x400.

**Comment by tmikaeld** [comment]
I requested it on #30 and suggested to make it more like Skype, one main window with two "sidebars", Facebook's web based messenger have the same "fold-in" making the sidebar show icons instead of full names.

**Comment by ConorIA** [comment]
I don't know how similar the underlying code is, but a user-intuitive approach might just be to make Wire adopt the mobile UI (Android + iOS) when the window is smaller than _x_ pixels in width.

**Comment by lipis** [comment]
Smaller window size would make sense on mobile devices, where we support only the native apps. In order to achieve a mobile view for our webapp requires quite a few design and implementation changes and currently, we don't have the resources or the need to do so. Maybe one day in the future.. but for now this now I'll close this issue.
