### ISSUE TITLE
Linux - Alt+Shift opens up window menu, not changes the language layout

### ISSUE THREAD

**Issue by darutse** [wireapp/wire-desktop#411]
non English speakers often using Alt+Shfit to change their language layout.
Window menu usually opens by ALT only, not Alt+Shift shortcut.
When pressing Shift+Alt, it works without opening window menu, my guess that it's a problem of web browser engine underneath the app.

**Comment by ffflorian** [comment]
Related to https://github.com/wireapp/wire-webapp/issues/733.

**Comment by lipis** [comment]
Pretty much.. let's continue there :)

**Comment by Sledge-Hammer** [comment]
This actually seems to be an electron bug (that's also present if the keyboard layout is switched with anything that contains Alt, not just Alt+Shift), also present in other chat clients in Linux and others have found a workaround for their code by adding an `&` in front of the menu labels (as in this example - https://github.com/vector-im/riot-web/pull/5000/files ) but I couldn't find anything similar in the source here...

I know this is an old issue but it's still present in the latest version and most of my Linux contacts (which are not native English speakers and need to change the keyboard layout multiple times during a relatively short conversation) want to move to another service, so please fix it because I really like Wire and don't want to be forced to change it with something else...
