### ISSUE TITLE
Update Notifications Bot

### ISSUE THREAD

**Issue by robotanarchy** [wireapp/wire-desktop#429]
Hello dear Wire developers,

could you make Otto the Bot send the users messages, when they need to
update their Wire version?
Both the desktop version and the non-Play-Store Android version do not
have any update mechanism, so this would be a simple to implement
trade-off.

In the long term, I hope for automatic updates for the desktop clients.

Thank you!

**Comment by lipis** [comment]
It would be a bit tricky to implement it as a bot.. because all of your clients would receive the message and then we'll have to have some sort of subscribe mechanism per user (not everyone would like this info). I think the best thing you could do is to subscribe to this feed: https://medium.com/@wireupdates where you get all the new releases plus the release notes.

**Comment by ThePlatzhalter** [comment]
Why would it be tricky to implement it as a bot? As long as the App checks for updates itself and provides a possibility to turn this behaviour off, there should neither be security nor technical difficulties. One just has to teach the bot to operate without a server.

**Comment by helenakos** [comment]
@ThePlatzhalter Thanks for the request. Although it's a very good idea, we don't currently have it on our near term roadmap - there are different clients and languages we would need to cater to so it's also a matter of resources. We are however working on bots and encouraging developers to build their own bots. If you would like to contribute please go to https://github.com/wireapp and search for 'bot' - there you can have a look at various projects we have going on.
