### ISSUE TITLE
Tray icon not shown on startup via Tweak tool (app still runs) [Linux/AUR]

### ISSUE THREAD

**Issue by giorgosioak** [wireapp/wire-desktop#431]
I have Antergos Linux (based on Arch) and i have installed wire via aur.

When i run the app myself or choose the Launch at StartUp its ok,
but if i add wire in Tweak Tools > Startup application it just don't show the icon, i can right click it and see menu, but not see it.

I can provide more feedback if needed 😃 

Thanks for Linux support.

Screenshot that system tray (top right) is not shown:
![screenshot from 2017-02-14 11-28-26](https://cloud.githubusercontent.com/assets/8626050/22923160/006654a2-f2a9-11e6-8546-599651c53f43.png)

**Comment by ConorIA** [comment]
I have this same experience with a few electron-based apps in Gnome (Zazu is another one). I'm not sure what the culprit is, but it isn't specific to Wire. The tray icon seems to appear when it feels like it. I see you're using the Top Icons Plus extension? I love that extension, but I haven't even thought to check if the icon appears without it. I will experiment a little in the meantime.

**Comment by giorgosioak** [comment]
Yeah, its TopIcon Plus. When i run it by myself its ok. Its very good, also shows the "have an unread message" icon. Very helpful. I can set to run wire after 1 minute of boot to make sure its ok, by using shell command. But that's not what i'm looking. :)

**Comment by lipis** [comment]
The version 2.11.2722 is finally released :) https://wire.com/download/

I'm not sure that this was related.. but I'll close it for now.

**Comment by ConorIA** [comment]
I'm not entirely sure that it was related (I've been using Budgie Desktop for a while now), but as I mentioned above, I don't think that it is a Wire-specific issue anyway.
