### ISSUE TITLE
Main window got blank after last update

### ISSUE THREAD

**Issue by coinnect-project** [wireapp/wire-desktop#4481]
In my company we have employees working on remote windows machines hosted on amazon workspaces. About 10 months ago we bought the license to have a wire team and every employee has his own workspace with windows app installed.
All worked well until the last weeks where, after the last wire update, the app randomly shows only the top menu but the main window with all the conversation disappeared.
The user is still logged in but the window is blank, clicking on any menu items doesn't show the realtive window. I tried to uninstall and reinstall many times, restart also workspace user is logged (ps there is a way to wipe all the data so after the installation I have to reinsert user and password????? i wanted to try a clean install but was impossibile)

Wire version: 3.21.3932
Operating system: windows server 2016
Which antivirus software do you have installed: trendmicro
What steps will reproduce the problem?

1.  open desktop app

What is the expected result?

show conversations

What is the actual result?

Blank window

Please provide any additional information below. Attach a screenshot if possible.

![wire_error](https://user-images.githubusercontent.com/38115092/98011927-cb030600-1df8-11eb-9c4f-817813e44288.png)

**Comment by Vlado-99** [comment]
I have very similar problem. I have installed Wire 3.21.3932 on 2 PC, both Windows 7 SP1 64-bit EN fully updated. While Wire works normally on one computer, on the second displays blank window with menu - permanently, not randomly.

There are some menu item working: Wire / Quit Wire and everything in Help.

What I tried (and what not helped me):
- restart PC
- uninstall (using Windows Control Panel) and new installation
- turn Windows Firewall off
- uninstall, delete folders `%USERPROFILE%\AppData\Local\wire` and `%USERPROFILE%\AppData\Roaming\Wire` and new installation

**Comment by coinnect-project** [comment]
> I have very similar problem. I have installed Wire 3.21.3932 on 2 PC, both Windows 7 SP1 64-bit EN fully updated. While Wire works normally on one computer, on the second displays blank window with menu - permanently, not randomly.
> 
> There are some menu item working: Wire / Quit Wire and everything in Help.
> 
> What I tried (and what not helped me):
> 
> * restart PC
> * uninstall (using Windows Control Panel) and new installation
> * turn Windows Firewall off
> * uninstall, delete folders `%USERPROFILE%\AppData\Local\wire` and `%USERPROFILE%\AppData\Roaming\Wire` and new installation

Maybe I didn't write the title very well. what I was saying that randomly wire started to be blank. But since that moment Wire is PERMANENTLY BLANK 😜 I also tried to delete those folders but when i reinstalled user was already logged in, so I think they save something else, maybe in so registry i don't know

**Comment by Vlado-99** [comment]
I did a brute force search on disk C: and in registry for patterns `*wire*`, `*electron*`, `*squirrel*` and found this Wire related items only:
- `%USERPROFILE%\AppData\Local\wire`
- `%USERPROFILE%\AppData\Roaming\Wire`
- `%USERPROFILE%\AppData\Local\SquirrelTemp`
- `%TEMP%\SquirrelSetup.log`
- `storage\default\https+++app.wire.com` inside my Firefox profile
- `HKEY_CURRENT_USER\Software\Classes\wire`
- plus few other crumbs like shortcuts inside `Desktop` and `Recent`

I deleted everything, but got same error.

It's a mystery.

**Comment by Vlado-99** [comment]
As a workaround I did:
- uninstallation of Wire and deletion of files, dirs and registry key I mentioned above
- installation of older version from https://github.com/wireapp/wire-desktop/releases/download/windows%2F3.20.3890/WireSetup.3.20.3890.exe
- deletion of file `%USERPROFILE%\AppData\Local\wire\Update.exe`
- restore of conversation backup created on other device

Wire works now and will not auto-update on this device (I hope).

**Comment by hamslam** [comment]
OS: Manjaro Linux 20.2
Kernel: 5.8.18-1

I'm having a similar issue with a white rectangular box appearing directly in the middle of my chat window. In the Options screen, it shows up more toward the right side of the window (see screenshots). If I quit Wire and reopen it, the white box goes away for a period of time. I'm uncertain how long, but it could be over an hour before it shows up again. If I turn off the Dark Theme, it's less noticeable but I can still tell that the box is there because it's not exactly the same color as the default background. 

I have uninstalled and reinstalled the same package version, but this did not solve the issue.  

This started with update 3.21.2936 on Linux. This was released on the same day as the Windows build 3.21.3923 in the author's original post. 

Attached are screenshots of the Wire chat window and options screen. 


![WireChat](https://user-images.githubusercontent.com/74149433/98472431-af14b100-21b8-11eb-84be-dece0b3d12ad.png)

![WireOptions](https://user-images.githubusercontent.com/74149433/98472067-11b87d80-21b6-11eb-84b7-87022bc6eba9.png)

**Comment by coinnect-project** [comment]
I found out that some users still had the 3.20.3890 version folder in %USERPROFILE%\AppData\Local\wire
Executing the app from here it opens and works fine showing all the conversations. All this without uninstalling.

**Comment by coinnect-project** [comment]
another little hint. If you don't have the previous version folder, you can just uninstall the bugged version and reinstall the previous without deleting the AppData/roaming folder. In this way when you open the app you have all the conversation without the need of a backup/restore

**Comment by bennycode** [comment]
Hello everyone,

We are trying to reproduce the problems that you are facing with seeing a blank page in our latest Wire Windows build (v3.21.3932). We have the suspicion that the Wire shortcut didn't get updated for you when running an update from Wire v3.20 to Wire v3.21, so that some of you  accidentially started v3.20 when v3.21 should have been started.

Do debug further we need some more information from you. Can you please start v3.21 from the Windows `cmd` with the following command? `%LOCALAPPDATA%\wire\app-3.21.3932\Wire.exe --devtools`

![image](https://user-images.githubusercontent.com/469989/104745537-81b32900-574e-11eb-8cf1-9b5fb8dff3a4.png)

When starting Wire with `--devtools`, it should show two windows (Wire app and Developer Tools). In the Developer Tools you can access a tab called "Console". After opening it, please enter `window.location.href` and report what it shows.

For me it is this:
> "file:///C:/Users/bn/AppData/Local/wire/app-3.21.3932/resources/app.asar/electron/renderer/index.html?env=https%253A%252F%252Fapp.wire.com%252F%253Fhl%253Den&focus=true"

**Screenshot**

![image](https://user-images.githubusercontent.com/469989/104744800-99d67880-574d-11eb-83ae-8e8b1ab11c2f.png)

**Comment by Vlado-99** [comment]
Hello.

What exactly I did:

- backup conversations
- run WireSetup.3.20.3890.exe to recover deleted Update.exe
- Quit Wire and start again to invoke auto-update
- still 3.20.3890 so wait some time
- Quit Wire and start again, blank window bug is here (version was updated to 3.21.3932)
- Quit Wire
- open cmd and run `%LOCALAPPDATA%\wire\app-3.21.3932\Wire.exe --devtools`
- blank window again and there is *only one window* opened (no console appears)
- investigating shortcuts:
  - on desktop: Target: `C:\Users\vlado\AppData\Local\wire\Wire.exe`, Start in: `C:\Users\vlado\AppData\Local\wire\app-3.20.3890`
  - in start menu: Target: `C:\Users\vlado\AppData\Local\wire\Wire.exe`, Start in: `C:\Users\vlado\AppData\Local\wire\app-3.20.3890`
- registry:
  - `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` contains `"C:\Users\vlado\AppData\Local\wire\update.exe" --processStart "Wire.exe" --process-start-args "--hidden"`

I don't need Wire on this particular PC right now, so I can wait some time if there will be another tests I can do.

**Comment by Vlado-99** [comment]
`C:\Users\vlado\AppData\Local\wire` contains both `app-3.20.3890` and `app-3.21.3932` now. Full list attached. (command, in Cygwin, was: `find /cygdrive/c/Users/vlado/AppData/Local/wire -type f -printf '%9s %T+ %p\n' >Wire-file-list.txt`).
[Wire-file-list.txt](https://github.com/wireapp/wire-desktop/files/5829570/Wire-file-list.txt)

**Comment by dkiper** [comment]
Hi,

window.location.href shows for me:

`file:///C:/Users/<user>/AppData/Local/wire/app-3.21.3932/resources/app.asar/electron/renderer/index.html?env=https%253A%252F%252Fapp.wire.com%252F%253Fhl%253Den&focus=true`

I discovered a workaround for this issue. I cannot run twice in row C:\Users\<user>\AppData\Local\wire\Wire.exe and
C:\Users\<user>\AppData\Local\wire\app-3.21.3932\Wire.exe. I have to start e.g. C:\Users\<user>\AppData\Local\wire\Wire.exe
first. If I quit from Wire then I can try restarting it using C:\Users\<user>\AppData\Local\wire\app-3.21.3932\Wire.exe.
I cannot use C:\Users\<user>\AppData\Local\wire\Wire.exe to restart Wire. This workaround works very often but not always.

Daniel

**Comment by Vlado-99** [comment]
Today I noticed my "blank window Wire" consumes more than 20% of CPU on i5 650 3.20GHz (I forgot to drop "Launch Wire on Startup" setting).
@dkiper's woraround doesn't work for me, btw.

**Comment by coinnect-project** [comment]
> %LOCALAPPDATA%\wire\app-3.21.3932\Wire.exe --devtools

Hi, I tried but dev tools does not open and wire is blank.

![wire_error_2](https://user-images.githubusercontent.com/38115092/105577503-61045800-5d7a-11eb-8718-b46029e722b0.png)

**Comment by kerouanton** [comment]
Hello. Same issue on my side. I didn't check this thread since now, but I investigated somehow during the last few days.

Blank display with v3.21.3932, no issue with an older version (I tried 3.17.3598)

- Differences within the binaries show the latest version uses Vulkan.dll, which supposes 3D rendering.
- Blank screen occurs on a virtualized Windows10Pro x64 20H2 running on VMware ESXi+ Vsphere 7.0.1 (latest version), and accessed with Microsoft RDP Client.
- I tried to tweak the VM settings to enable/disable 3D acceleration, and to enable/disable Hardware/Software rendering, but that doesn't fix the issue.

I really suspect the issue is due to the use of Vulkan 3D rendering over RDP. Meanwhile I had to rollback on a previous version of Wire.

Regards,
Bruno Kerouanton

**Comment by coinnect-project** [comment]
> Hello. Same issue on my side. I didn't check this thread since now, but I investigated somehow during the last few days.
> 
> Blank display with v3.21.3932, no issue with an older version (I tried 3.17.3598)
> 
> * Differences within the binaries show the latest version uses Vulkan.dll, which supposes 3D rendering.
> * Blank screen occurs on a virtualized Windows10Pro x64 20H2 running on VMware ESXi+ Vsphere 7.0.1 (latest version), and accessed with Microsoft RDP Client.
> * I tried to tweak the VM settings to enable/disable 3D acceleration, and to enable/disable Hardware/Software rendering, but that doesn't fix the issue.
> 
> I really suspect the issue is due to the use of Vulkan 3D rendering over RDP. Meanwhile I had to rollback on a previous version of Wire.
> 
> Regards,
> Bruno Kerouanton

yes. My problem is also on virtual machines...access is done by amazon workspace client wich use PCoIP protocol

**Comment by Vlado-99** [comment]
Problem (blank window, no devtools) still persist in 3.22.3993.

**Comment by Vlado-99** [comment]
@kerouanton mentioned vulcan.dll.
I decided to borrow another graphics card, here are results:
My default graphics is Intel HD Graphics with driver 8.15.10.2119 from April 21, 2010 (Intel Core i5 650 CPU) - Wire doesn't work.
Borrowed graphics was nVidia GeForce 9800 GT. With Microsoft driver 8.15.11.8593 from May 14, 2009 Wire doesn't work.
With nVidia driver 9.18.13.4144 dated Feb 3, 2015 - Wire finally works!
I have to buy newer graphics card!

**Comment by Vlado-99** [comment]
I suggest to improve Wire - add check and report missing prerequisites. It may save days of life to someone in future.

**Comment by coinnect-project** [comment]
> @kerouanton mentioned vulcan.dll.
> I decided to borrow another graphics card, here are results:
> My default graphics is Intel HD Graphics with driver 8.15.10.2119 from April 21, 2010 (Intel Core i5 650 CPU) - Wire doesn't work.
> Borrowed graphics was nVidia GeForce 9800 GT. With Microsoft driver 8.15.11.8593 from May 14, 2009 Wire doesn't work.
> With nVidia driver 9.18.13.4144 dated Feb 3, 2015 - Wire finally works!
> I have to buy newer graphics card!

It's nearly clear that the problem is related with graphic rendering. But on virtual machines/cloud servers 99% of the time the grafic card is not present so this bug will never be fixed....let's wait some signs, they wrote 2 months ago. I think that this bug is very easily reproducible now

**Comment by Vlado-99** [comment]
@coinnect-project : Virtual / cloud is not my case. I'am on bare metal (HP Elite "office class" PC). I understand my hardware is a bit old and if there are reasonable arguments (need of newer OpenGL API or whatever) I understand that upgrade on my side is only way. (Or stay with older Wire version.)

**Comment by coinnect-project** [comment]
> @coinnect-project : Virtual / cloud is not my case. I'am on bare metal (HP Elite "office class" PC). I understand my hardware is a bit old and if there are reasonable arguments (need of newer OpenGL API or whatever) I understand that upgrade on my side is only way. (Or stay with older Wire version.)

I know but I'm saying that at least with physical you can change the device or hw, on cloud I think the problem is not fixable..

**Comment by bennycode** [comment]
I am very impressed with the analytical work that is being done here. Thank you so much for your reports & efforts!

At Wire we are also puzzled about the whitescreen issues. Our desktop apps are based on the [Electron framework](https://www.electronjs.org/). We do not modify Electron's native code and only update the Electron version from time to time. The usage of "Vulkan.dll" must have been introduced by the Electron team.

As of today, we cannot reproduce the whitescreen issues on our end, so we are very thankful for any hint in this direction. The dominant theory seems to be that the whitescreen issues show up due to graphic card issues. Let's collect all of the information on this, so that we can forward this report to the Electron team.

Wire Version | Operating System | Graphics Card | Graphics Card Driver | Result
:---:|:---:|:---:|:---:|:---:
3.22.3993 | Windows 10 Pro | Radeon RX 590 | AMD Adrenalin 21.08.2020 | OK
3.22.3993 | Windows 10 Pro | Intel HD 520 | Intel 20.19.15.4463 | OK

Please comment your configurations, so I can update this table.

@Vlado-99, what's the series of your Intel HD Graphics card? You are using Windows 7 SP1 64-bit, is that correct?

**Comment by coinnect-project** [comment]
> I am very impressed with the analytical work that is being done here. Thank you so much for your reports & efforts!
> 
> At Wire we are also puzzled about the whitescreen issues. Our desktop apps are based on the [Electron framework](https://www.electronjs.org/). We do not modify Electron's native code and only update the Electron version from time to time. The usage of "Vulkan.dll" must have been introduced by the Electron team.
> 
> As of today, we cannot reproduce the whitescreen issues on our end, so we are very thankful for any hint in this direction. The dominant theory seems to be that the whitescreen issues show up due to graphic card issues. Let's collect all of the information on this, so that we can forward this report to the Electron team.
> 
> Wire Version	Operating System	Graphics Card	Graphics Card Driver	Result
> 3.22.3993	Windows 10 Pro	Radeon RX 590	AMD Adrenalin 21.08.2020	OK
> 3.22.3993	Windows 10 Pro	Intel HD 520	Intel 20.19.15.4463	OK
> Please comment your configurations, so I can update this table.
> 
> @Vlado-99, what's the series of your Intel HD Graphics card? You are using Windows 7 SP1 64-bit, is that correct?

Reproduce should be easy, did you tried to set up a windows virtual machine and connect to it through remote protocols? 
However Amazon workspaces aka Windows server 2016 with graphic card listed in device management as Teradici PCoIp WDDM driver...

**Comment by dkiper** [comment]
Hey,

I have similar problems on KVM machine with QXL paravirtual graphic card with spice protocol.
Though I use it mostly over RDP. It is latest and greatest Windows 10.

Daniel

**Comment by bennycode** [comment]
We've setup "Windows Server 2019 (1809)" today and are now able to reproduce the problem via Remote Desktop Connection:

- Wire 3.19.3731 (Electron 9.1.2) works
- Wire 3.22.3993 (Electron  10.3.1) shows a whitescreen

I created a small "[electron-gpu-util](https://github.com/bennycode/electron-gpu-util)" which shows the webpage `chrome://gpu/` to dump information about the Graphics card.

On my desktop system (where Wire v3.22 works), it looks like this:

![image](https://user-images.githubusercontent.com/469989/110807104-fef8a700-8282-11eb-8a36-324db2920252.png)

The failing remote desktop session shows this:

![image](https://user-images.githubusercontent.com/469989/110807240-1f286600-8283-11eb-8c1e-8b3478f5e41e.png)

Surprisingly, the Remote Desktop session is able to show the [electron-gpu-util (based on Electron 9)](https://github.com/bennycode/electron-gpu-util/releases/tag/v1.0.0) and [electron-gpu-util (based on Electron 10)](https://github.com/bennycode/electron-gpu-util/releases/tag/v1.0.1). I was expecting it to fail rendering a webpage with the Electron 10 build.

We are now checking what has been changed in our desktop app code when upgrading from Electron 9 to Electron 10:
- https://github.com/wireapp/wire-desktop/compare/windows/3.20.3890..windows/3.21.3932

**Comment by coinnect-project** [comment]
yes Wire 3.19.3731 its the last working version ;) so you can compare only from this to 3.21.3932 if it results easier to do

**Comment by Vlado-99** [comment]
> 
> @Vlado-99, what's the series of your Intel HD Graphics card? You are using Windows 7 SP1 64-bit, is that correct?

@bennycode :
Correct.
About graphics card Hwinfo64 says:
Video Chipset:                        Intel HD Graphics
Video Chipset Codename:      Ironlake
Video Memory:                      3894842 KBytes
Video Card:                            Intel Havendale/Clarkdale Processor - Integrated Graphics Controller [K0] [Hewlett-Packard]
Video Bus:                              Integrated
Video RAMDAC:                     Internal
Video BIOS Version:               1914 PC 14.34  10/15/2009  11:33:22
Hardware ID:                          PCI\VEN_8086&DEV_0042&SUBSYS_2A9C103C&REV_18
Driver Manufacturer:               Intel Corporation
Driver Description:                  Intel(R) HD Graphics
Driver Provider:                      Intel Corporation
Driver Version:                       8.15.10.2119
Driver Date:                            21-Apr-2010

**Comment by Vlado-99** [comment]
@ffflorian WireSetup-3.23.4029-gpu-check.exe works for me. All screens (pages) are displayed properly. Perfect job. Thank You!

**Comment by ffflorian** [comment]
@Vlado-99 great to hear! Thanks for testing.

**Comment by dkiper** [comment]
Hey,

It looks it works for me too. Thanks a lot for taking a stab at the issue!

Daniel

**Comment by coinnect-project** [comment]
tested on one of the amazon workspace. 
It works.

**Comment by ffflorian** [comment]
We just released v3.24 for Windows, Linux and macOS which includes the fix for the blank window.
Thanks for the patience everyone!
