### ISSUE TITLE
Camera not turned off on OS X when switching to audio call

### ISSUE THREAD

**Issue by sirnacnud** [wireapp/wire-desktop#48]
I was doing a video call on my Macbook Pro and when we switched to audio only, the camera was left on as indicated by the green light. My friend on the other end experienced the same behavior. The cameras weren't turned off until we ended the call. We are both using version 2.10.2652 of Wire on OS X.

**Comment by gregor** [comment]
Thanks for bringing this to our attention. Currently this by design. Looking at it techincally: We would not only have to grab a new camera stream but do a full cycle of the SDP negotiation when you turn the camera back on. This would at 2-4 seconds to every time you turn on the camera and is failure prone. Therefore we decided to essentially mute the camera in a scenario like this. The camera image is not submitted via the stream. We can instantaneously turn the camera back on in the call but have to live with the side effect that the camera is never fully turned off as the camera light is indicating.

This limitation is a result of the implemetation status of webRTC in the underlying Chrome browser used in our app based Electron. Chrome does not yet support the RTCRtpSender extension which provides a RtcRtpSender.replaceTrack(). (https://www.chromestatus.com/feature/5347809238712320) Once they ship this in the coming months we can adjust the experience and fully turn on and off the camera without hurting the UX due to the long renegotiation periods.

**Comment by sirnacnud** [comment]
Thanks for the technical explanation, hopefully Chrome adds support soon. My concern is that leaving the camera on for extended periods of time (when it isn't needed) could be a battery drain for laptops.
