### ISSUE TITLE
Windows App freezes

### ISSUE THREAD

**Issue by trustno1foxm** [wireapp/wire-desktop#486]
Hello!

I have a problem by using the windows desktop app. It freezes very often :/ Any suggestions?
Thx in advance!

so long!

**Comment by lipis** [comment]
Can you give us more info, like what version of Windows are you using? Is there anything in particular you are doing usually when it happens..?! It's a bit hard to guess everything :D

**Comment by trustno1foxm** [comment]
I am sorry about that! ;) Of course:
Windows 10 Pro, Version 1607, Build 14393.693
Wire: 2.11.2712

I only works for about some minutes. What I am doing, hmm just using Chrome and browsing through the internet.
Thx!

so long

**Comment by mythsunwind** [comment]
There might be a workaround for the freeze:
Go to Wire | Settings | Options and set Notifications to Off

Can you check if the freeze still happens after that?

**Comment by Quantum00** [comment]
Can confirm the issue happens and is fixed after setting Notifications to Off. Please fix

**Comment by trustno1foxm** [comment]
I am still testing without Notifications, but your workaround seems to work^^
Thx so far!

**Comment by trustno1foxm** [comment]
I just got an update -> 2.12.2729, but the bug still exists.

so long

**Comment by azlux** [comment]
Indeed, same here on 2 different computers. If there a way to have the debug, I can reproduce it really easy.

**Comment by mythsunwind** [comment]
That would help us a lot, since we have no machine where we could actually reproduce it. It seems to me that it's related to a certain hardware or software setup, but if not you can help us by getting some logs.

In `/User/<your usernam>/AppData/Roaming/Wire/` you can find two files `console.log` and `console.log.old`. They include every error that is thrown in the browser console.

If the native app part is the reason for the bug, the error might be logged somewhere else though. Type `eventvwr.msc` into the windows search, go to "Windows Logs" | "Application", Clear the log, reproduce the issue and look out for log events with an "Error" or "Warning" level.

**Comment by azlux** [comment]
Nothing into log, just this message : 
`
{"level":"info","message":"Wire Version 2.12.2729","timestamp":"2017-03-17T18:05:14.786Z"}
{"level":"info","message":"Wire Version 2.12.2729","timestamp":"2017-03-17T18:05:16.605Z"}
`

The windows log show : https://azlux.fr/bin/?0d9278899fe57abf#4J/Zk2bfazrOnxof+YnaF7rFShw0c8VkFqDZq4ucw28=

The report mentionned into logs is here : https://azlux.fr/bin/?dcbf16d8f5a91884#HI+5Y0lC/QtL18SVL0UVkxa918pehVbZ4SGQ/4VoXpE=

It look like to append when we don't click on the windows notification of Wire.

**Comment by spmdc** [comment]
For me it only freezes for a while after receiving a new message.

Windows 10 Enterprise 64-bit, Version 1607, Build 14393.953
Wire 2.12.2729

console.log is empty
When I run "npm test" in a local copy of the repository I get the following error:

1) tray #updateBadgeIcon() should update badge according to window title:
     Uncaught TypeError: Error processing argument at index 0, conversion failure from <...>\wire-desktop\node_modules\electron\dist\resources\default_app.asar\img\taskbar.overlay.png
      at Timeout.setTimeout [as _onTimeout] (electron\js\menu\tray.js:72:11)

A similar Javascript error sometimes shows up after the freezes.

Unfortunatly I have no experiance with debugging electron apps, but would be willing to run additional tests or provide information.

**Comment by mythsunwind** [comment]
I think i found the freeze issue in the electron issue tracker. The report matches your observations:
https://github.com/electron/electron/issues/7831

According to the issue, it happens for a few users on Windows 10 when the notification object gets customized onclick handlers.

The same users who experience this bug also report the issue for other applications based on electron:
https://github.com/saenzramiro/rambox/issues/402

**Comment by 2001db8** [comment]
I also have this issue in Win7 after receiving a new message. Since then exiting Wire and restarting it the error immediately comes up again and I end up with a wire.exe process running but no Wire window. Affects both the current desktop version and WireInternal beta.

![wire_dead](https://cloud.githubusercontent.com/assets/9391840/26761758/085d771a-4936-11e7-9b9a-4db97774ae1a.jpg)

**Comment by kunago** [comment]
It started happening to me as well, running Windows 10, 64-bit.

**Comment by spmdc** [comment]
Why was this closed? It still appears in 2.15.2750, 2017.08.31.1421

Atm I get theses error messages every time I change contacts or any window actually (e.g. switching through tabs in settings).
And I still have notifications completly disabled, because it also get them when someone messages me.

The error messages look very similar to the one posted above.

**Comment by BVollmerhaus** [comment]
Same problem here, Wire (3.0.2828) still freezes when receiving notifications on Windows 10. Please re-open. This issue is a duplicate of #179; both are closed even though this issue definitely needs more investigation.

**Comment by BVollmerhaus** [comment]
Same issue here, Wire (3.0.2828) still freezes when receiving notifications on Windows 10. Please re-open. This is a duplicate of #179 which is also closed, even though the issue definitely needs more investigation.

**Comment by mythsunwind** [comment]
We could track down some of the freezes to outdated drivers of sound cards on Windows 10. After updating their sound card drivers to the current ones provided by Microsoft directly (not from the vendor of the sound card) the freezing stopped. Can you please check which sound card is build into your machine and if you have the latest Windows 10 with the latest drivers installed? (Open the device manager and check the sound card section)

**Comment by BVollmerhaus** [comment]
> Can you please check which sound card is build into your machine and if you have the latest Windows 10 with the latest drivers installed? (Open the device manager and check the sound card section)

I am using an external USB DAC with the standard USB audio drivers included in Windows 10. All my other drivers and Windows itself are up-to-date. Unfortunately I can't reproduce the issue right now but I'll try to unplug my DAC the next time it appears and see if it makes a difference.
