### ISSUE TITLE
Alt + Number chat window switching

### ISSUE THREAD

**Issue by turbotum** [wireapp/wire-desktop#503]
HexChat IRC client has a feature I quite like and have gotten used to and comfortable with, where you can hold alt and press a number from 1 to 9 to switch chat window. In Wire, you'd be able to hit alt 1 to see your most recent or unread chat and stuff like that.

**Comment by lipis** [comment]
That's quite a good idea.. :)

**Comment by GopianiS** [comment]
Yes I like this very much too! Just how Chrome does Ctrl + <Number> to switch tabs

**Comment by maximbaz** [comment]
Related: https://github.com/wireapp/wire-webapp/issues/733

I'd be happy to see either option, as long as it's usable and does not conflict with other common functionality.

**Comment by that1communist** [comment]
You should try having a keyboard shortcut list, rather than necessarily this, because this would massively interfere with my WM.

**Comment by bennyn** [comment]
Very good input! Also configurable shortcuts would be nice (so that everyone can use his/her favorite). 

Unfortunately our product owners don't plan to redesign keyboard shortcuts any time soon (https://github.com/wireapp/wire-webapp/issues/94#issuecomment-290714090). I will close this ticket here until we have other news.
