### ISSUE TITLE
Desktop release lagging

### ISSUE THREAD

**Issue by chriseomi** [wireapp/wire-desktop#5394]
Wondering if `wire-desktop`  is going to receive a little tlc sometime in the nearby future.

Last release was 5 months ago in June. Whereas the `wire-web` and the Mac App store version are receiving regular updates. 

Happy to help with testing or devopsy things if needed.

**Comment by artenaki** [comment]
That's a good thing. Many people don't like frequent updates (like Signal). Stability and backward compatibility are comforting.

**Comment by marvinhagemeister** [comment]
> That's a good thing. Many people don't like frequent updates (like Signal). Stability and backward compatibility are comforting.

Disagree. There are some very user visible bug fixes queued that haven't been released yet. Most notably [#5164](https://github.com/wireapp/wire-desktop/pull/5164) which makes using the desktop client unusable on my Macbook.

**Comment by fluffypony** [comment]
I basically have stopped using Wire on my Macbook. It's an insane battery hog because of #5164 - and since it's not a native Apple Silicon binary (or a Universal Binary) its impact is like 20% - 30% worse as it has to be virtualized through Rosetta 2. They also haven't opted in to allowing the iOS version to be installed on macOS, which might partially solve this issue.

**Comment by artenaki** [comment]
I have a wire-desktop on Linux i686 on Pentium 4:
- at idle 10%
- active 15%
But I don't see this as a problem (except for the long startup time), since I only run Wire a few times a day. It is not running all the time. Similarly, I didn't keep telegram-desktop open all the time when I used it.

If this problem is fixed in git, why don't you compile new version yourself?

**Comment by fluffypony** [comment]
@artenaki I did indeed try building bins - but it launches a white screen with a spinning wheel, and I don't really have time and energy to debug why it never goes beyond that.

![Screen Shot 2021-11-23 at 6 31 30 PM](https://user-images.githubusercontent.com/1944293/143149946-9506c556-54aa-4033-ad32-459714cd65e6.png)

The challenge here is that Wire is more Cathedral and less Bazaar, and given the relatively high cost we pay for our Wire Enterprise license every month I'm just a little disappointed that they can't get regular updates out. We're seriously considering switching to self-hosted Matrix / Riot given this debacle + the lack of an Apple Silicon binary for macOS.

**Comment by rkapur-gds** [comment]
Building the latest release for arm64 worked for me:
```
git clone https://github.com/wireapp/wire-desktop.git
cd wire-desktop
yarn
yarn build:macos:arm64
cp wrap/build/Wire-mas-arm64/Wire.app /Applications/Wire.app
open /Applications/Wire.app
```

**Comment by tlebon** [comment]
> Bumping this to see if a native Apple Silicon binary is on the horizon!

bit late but this has been included in the latest release.

**Comment by tlebon** [comment]
I'll close this for now, as the topics mentioned in this issue have been addressed.
1. apple silicon binary
2. Electron upgrades
3. #5164 

If any new issues crop up in the desktop application, please open a new ticket!
