### ISSUE TITLE
Conversation not sorted correctly

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-desktop#58]
. Wire 2.10.2652 / Win7x64
Steps to repro:
- bob sends msg to alice
- bob receive message(answer) from alice
(<--- all fine till here ....)
- bob sends again a message to alice 
<--- in further conversations: from here on, bobs messages are not shown as last message! all messages get sorted above alice's messages.
 
i did not have this issue since last update.

**Comment by gregor** [comment]
Have you checked whether your system clock is off? For outgoing messages we currently use the local time, for incoming messages we rely on the server time. If your system clock is off, message order will be off.

**Comment by peterpanondrugs** [comment]
This solved my problem. 
Buuuuut strange is, that i used wire without problems since 1month? and i never had this issue before.

**Comment by gregor** [comment]
With the release from last week message you send will be displayed in the UI much earlier. You will see them greyed out while they are still sending. Technically we would have to update the timestamp of the messages in the database once they are sent and we receive the updated timestamp from the backend. Due to our database format this is a little tricky right now. In order to ship the feature due to the much nicer user experience we decided to ship it with the known limitation when your system clock is off. We have to do some work on the database schema before we can improve the experience in these scenarios as well.

**Comment by peterpanondrugs** [comment]
thx fyi. feel free 2 close.

**Comment by tmikaeld** [comment]
I hope this can be fixed, I tested this between Windows 10 and OS X where both have time-sync on and the Windows Wire will get the wrong sort order of messages.

**Comment by fernandodrf** [comment]
I have the same problem, even though the system clock is correctly synced. However, I haven't found out how to check if the system clock is off. Any suggestions?
Thanks!
