### ISSUE TITLE
Is Wire Desktop susceptible to this Electron Vulnerability like Teams, Slack and Discord?

### ISSUE THREAD

**Issue by find-marc** [wireapp/wire-desktop#5914]
> At the Black Hat cybersecurity conference in Las Vegas on Thursday, the researchers presented their findings, detailing how they could have hacked people who use Discord, Microsoft Teams, and the chat app Element by exploiting the software underlying all of them: Electron, which is a framework built on the open source Chromium and the cross-platform javascript environment Node JS. 

More info here: 
[https://www.blackhat.com/us-22/briefings/schedule/index.html#electrovolt-pwning-popular-desktop-apps-while-uncovering-new-attack-surface-on-electron-26322](https://www.blackhat.com/us-22/briefings/schedule/index.html#electrovolt-pwning-popular-desktop-apps-while-uncovering-new-attack-surface-on-electron-26322
)
[https://www.vice.com/en/article/m7gb7y/researchers-find-vulnerability-in-software-underlying-discord-microsoft-teams-and-other-apps](https://www.vice.com/en/article/m7gb7y/researchers-find-vulnerability-in-software-underlying-discord-microsoft-teams-and-other-apps)

**Comment by J-Brk** [comment]
Likely, yes. Since Wire on Desktop seems to use Electron as well. The problem you mentioned however is already fixed so shouldn't be an issue any longer. "The bugs were fixed before the researchers published their research. "

"One of the researchers who found these vulnerabilities said [...]" [...] he doesn’t run Electron apps, instead opting for using apps [..] inside his browser, which is more hardened against hackers."

I don't think there is much Wire can do in this case since. There are some things you can do however:  if you are really concerned, I recommend you switch to using Wire in a browser, optimally with some additional sandboxing.

**Comment by tlebon** [comment]
This appears to be deprecated so i am closing it.
