### ISSUE TITLE
App fails to scroll when decreasing horizontal size below threshold

### ISSUE THREAD

**Issue by schlichtanders** [wireapp/wire-desktop#625]
Thanks for this project!

in windows when making the window very small, the scroll up/down bar just disappears and in all PREFERENCES section scrolling does not work either then.
![wire_scrollbar_missing](https://cloud.githubusercontent.com/assets/4255480/25709285/2f5dc2a8-30e9-11e7-8138-0eb77c511961.PNG)

Interestingly scrolling in the main chat window still works, however also here no scroll bar is visible.
thanks

**Comment by dwt** [comment]
Seeing this too - can I provide any additional details that you need?

**Comment by ddobrev** [comment]
Since my issue at https://github.com/wireapp/wire-desktop/issues/981 was closed, hopefully as a duplicate, I'll describe the effects of the workaround given there in here.
This was supposed to be fixed by changing the width of the app. However, it only works in part. The vertical scroll does appear, grabbing it and scrolling up and down works and so does the scrolling up with the mouse wheel (or, in my case, sliding with two fingers on the trackpad). However, scrolling down with the mouse wheel/sliding does not.

**Comment by ddobrev** [comment]
The same happens with any search results, not just images and links. It's quite annoying and should not be that difficult to fix because you do have screens, such as the chat area, where vertical scrolling works properly.

**Comment by gregor** [comment]
With the release https://github.com/wireapp/wire-webapp/releases/tag/2018-02-16-07-54 this should be fixed everywhere in the app.
