### ISSUE TITLE
Suggestion: timed messages defaults

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-desktop#627]
Two part suggestion.

The type of timer associated with new conversations should be a global default. Otherwise one gets used to timers being on then finds out that timers are off in some other context and has to manually delete. Whatever your expectation is then, you can rely on it. 

I think the best choice for an out of the box default on a messenger that is intended to be secure would be a 1 day timer. However, this can confuse newbies who don't understand where their message history went. So I would relent and say "no timer" as a default, let people learn the software, and after set a default timer for their messages. But this will be very useful I think as it will prevent accidentally sending messages with no timer and not noticing. 

Second part of the suggestion:

Currently timers can be set for:

5, 15, 30, 60 seconds
5 minutes
1 day

Granularity here is weak... I think having 4 choices at 60 seconds and below, and then one choice above 5 minutes has some unserviced utility gaps. I would suggest:

10, 30, 60 seconds 
5, 60 minutes
12 hours, 24 hours

As a bit more utility and fill in the gap between 5 mins and 24 hours.

**Comment by gregor** [comment]
Thank you for your suggestion. We will consider it when revisiting our timed messages feature. At this time there are no immediate changes planed. The request will be tracked internally and I will close this issue.

**Comment by libBletchley** [comment]
1 day is far too short.

Timed messages are really the only way to keep a clean inbox since there is no batch delete feature.  It's bizarre that wire has:

5s, 15s, 30s, 1m, 5m, 1d

As @dbquarrel says, it's a bit bizarre to have all those steps below 5 min & then only 1 day for those trying to keep a clean history.  A recipient glances at a msg while driving, then they have only 1 day to get back to it & reply.

We need 1 week.

**Comment by gregor** [comment]
Definitely too short. We are working on the feature right now. You can see the new timings in https://github.com/wireapp/wire-webapp/blob/dev/app/script/ephemeral/ephemeralTimings.js. They will be part of the next release.

**Comment by dbquarrel** [comment]
Because of past attitude problems via the official Wire stance toward serious issues like this, I have been evaluating other options as a means of moving my team off of Wire. The recent reconsideration of timers after 2 years of complaining about them from me and others, is making me pause and reconsider using Wire again, or at least giving Wire a bit more time. I really do not like the general attitude of this team though towards dismissing serious issues as non-issues or non-priorities. 

That said I have a lot to say on this in addition to past complaints based on evaluation of WickerMe which runs circles around Wire's implementation to date. Some lessons can be learned from this and future development should be indicated.

Some comparison to WickerMe in this feature area can be enlightening. There are two issues at stake, the first is the concept of Expiration and the concept of Burn After Reading. Expiration sets a total TTL (Time To Live) on a message from time of receipt. Burn-After-Reading sets a TTL that starts after the message is read. The message is deleted when the lesser of the two thresholds is passed. One or both or neither can be set by the sender based on the use case. Wire's "Expiration" is equivalent to Burn-After-Reading.

The benefits here are that an Expiration TTL in Wicker style means that if a device is lost, the message is not left indefinitely in an accessible state. A received Wire message that is not read + lost device --> that message exists into the far future. If someone recovers the device and is able to open it, then all messages will spring forth. With an expiration TTL the message will not be accessible past a hard limit that begins after the message is sent. The burn-after-reading timer then does the same thing that Wire is doing now. Combining the two is very powerful.

The second paradigm that is weak is granularity as I've been complaining about for a couple of years.

There is no practical difference between 5, 10 and 30 second expiration unless you are maybe working for a three letter agency, and if you are, you are not using Wire. We need granularity between the 5 minute and 1 day period and as can be seen some people want more than 1 day. Time periods can be thought of as "fast expire", "medium expire", "slow expire", and "glacial expire" depending on the person's needs. 1 minute and below is fast expire. 5m is medium expire. 1 day is slow expire. And there is nothing in the glacial expire category. So there are many options currently, maybe too much for fast expiration, and not enough in the other buckets.

Looking again to WickerMe, here are the time periods available to the user:

Fast expire: 1,2,3,4,5,6,7,8,9,10,20,30,60 seconds

Medium expire: 2,3,5,10,20,60, 120 minutes

Slow expire: 3,4,5,6,12,24 hours

Glacial expire: 2,3,4,5,6 days

Now, that is a nice set of options and I would think that every user can find a use pattern within this, especially with the two forms of expiration.

If you need expiration more than 6 days it's almost the same as email, -or-, you can just turn it off.

Sample use patterns:

1) 6 day expiration + 12 hour burn after reading -> this would set a 6 day cap, so that if someone didn't ever read their messages it will go away. 12 hours it can linger after they read it.
2) expiration turned off + 6 day burn after reading -> almost like email, cleans up very slowly

3) 1 hour expiration + 30 second burn after reading -> most likely an interactive conversation with someone else who is multi-tasking


Active vs. Passive reading

There is one additional feature that is good in WickerMe that should be adopted, though I don't use it.

If I am using Wire on my desktop and I go to the toilet and come back, if my correspondent sent me some 10 second expiration messages, and I was active in the conversation (i.e. it is up), then my machine will consider those messages read and then delete them after 10 seconds. I won't ever know they are there.

I am OK with passive reading in general. But WickerMe allows the user to decide if reading should be active or passive.

In the case of active reading:

1. a message arrives and is marked as arrived, but remains encrypted
2. the expiration timer starts
3. user taps on the message
4. message is decrypted
5. burn-after-reading timer starts
6. message is deleted when the lesser of expiration or burn-after-reading timer expires

Now we can see the power of this paradigm.

The case of user going to the toilet, and messages silently appearing and vanishing without him ever knowing it no longer exists if a user chooses active reading. User will then come back, see 10 messages waiting, tap them and read them, starting the burn timer, and messages will expire as expected.

Those messages won't persist forever though because of the expiration timer, if I go to the toilet, have a heart attack and died, and my body is found 7 days later, the expiration timer will have cleaned up those messages before they are ever decrypted and read.

Or, if I don't care, I can just engage in passive reading in which case it will work just like Wire works now, however, if I am not tuned to the conversation then the expiration timer will still clean up messages due to the hard cap added by the sender, should the sender care about setting it.

----

Overall it is a very serious and solid implementation of message expiration and I think a good paradigm to follow.

Furthermore the implementation has used about 10% of the processor speed that Wire does while having a similar code base (I think Javascript based though I am not sure on WickerMe). I haven't tested the new implementation yet. But, any improvements of Wire in this area are going to be warmly embraced by me because the status quo has been so bad.

----

Where WickerMe fails vs. Wire is that the UI interactivity is a bit poor, one incredibly bad choice for instance is to have spellcheck on the fly triggering with every character typed. This makes "every word wrong" until it's done typing and then is highlit in red and finally goes black when the word is done. This almost makes me have epileptic fits and is highly distracting. For this one reason alone it is not usable as there is no apparent way to turn this off.

It shows again the problems of modern design, where there are few user-options and a lot of programmers with this same basic programming problem of "hey, nobody will ever want to do this" ---> which forces applications to be bound to the limitations of programmer imagination. That has always been bad. But these days programmers prioritize what they want vs. what users need (i.e. the Apple model), where users are all expected to conform to a closed set of functionality.

Only now for instance is Apple starting to adopt reverse video as more people call for "dark mode", while dark mode has been available in the X window system since it was built and almost all sane programmers using X had reverse video on since the 1980s. Light backgrounds and dark text is a carryover from people who are used to paper, and so the screen should look like paper, and as a result generations of people were forced to deal with blinding white backgrounds that had no real utility sense vs. dark backgrounds and light text which is far easier on the eyes. This is a limit of programmer imagination forced onto the users, instead of letting the users choose what is better.

I wish wire though would leave more options in the hands of the users. I wish I could for instance make this messaging screen take up a lot less desktop space. Back in the ICQ days with much, much smaller screens to use, say 1024x768 of desktop space, we could make ICQ still take up just a tiny chunk of real estate. Now, with massive displays and 4-8x this real estate available, an instant messenger may demand 40% of the desktop in minimal configuration.

This is terrible.

So much utility can be achieved if there was some focus on basic functionality instead of bells and whistles that may seem sexy to the marketing department.

These are the most important features of a secure messenger:

1. Secure transport (I think this is tackled well)
2. Message expiration (this is part and parcel of security, and Wire partially fails traditionally)
3. Ergonomics (Wire and most others fail horribly compared to prior-generation messengers as current-era programmers have completely missed the target, worrying more about "how does my transparent background look" instead of "is it really necessary to use half of the desktop to do this?")

Refocusing on the basics will make this application 200% better.

**Comment by libBletchley** [comment]
The GUI can always be improved, but I think there's more bang-for-buck if something like a Bitlbee plugin were created.  In principle a backend-GUI separation would enable users to choose whatever IRC/IM client they like, and Wire devs could then be relieved to some extent from the effort of GUI improvements.

**Comment by neongreen** [comment]
@libBletchley if you're familiar with the topic, could you explain what would be the pros and cons of making a Bitlbee plugin vs making a libpurple transport plugin? (As I'm not familiar with either but am curious if I should try to pitch the idea internally)

**Comment by libBletchley** [comment]
@neongreen 

Libpurple is a bitlbee library that supports many protocols. Some of those protocols are also built-in to bitlbee, so the redundancy is confusing. I've not felt the need to install libpurple, so I can't really elaborate on the pros and cons. But there's some comparison here:

https://wiki.bitlbee.org/HowtoPurple

I think the significant factor to consider is that Bitlbee is an IRC server, and thus imposes IRC limitations. Wire-bitlbee users would be choosing a fast, convenient and highly scriptable UI at the cost of feature poorness. Media would have to be replaced with a tag of some kind, and either give users a way to get the graphical content outside of IRC, or (perhaps more realistically) launch the Wire app just in those situations.

Always having IRSSI running in a Gnu Screen session, with highlights appearing on interesting texts is great. Nice to not have to login to Twitter and just automatically have the timeline running, for example, until a msg appears that needs a GUI interaction.  It's useful that it cuts down dramatically on the need to mouse around in a gui.

One factor Wire devs would face is how to handle timed msgs. Once the IRC server (bitlbee) sends a msg to the IRC client, it can't remove it AFAIK.. that's a one-way operation.  So there would have to be a decision whether to withhold all timed msgs, or violate the sender's wishes.

**Comment by neongreen** [comment]
@libBletchley 

> So there would have to be a decision whether to withhold all timed msgs, or violate the sender's wishes.

Unfortunately, they both violate expectations of "normal users" in a pretty heavy way -- i.e. when you know that someone on your team uses Bitlbee, you have to be pretty careful:

* If the "withhold timed msgs" option is picked: I actually experienced a similar thing with Slack -- they had an IRC gateway but it didn't handle threads or message edits, and so we had a bunch of team members who were missing on chunks of information without anyone being aware of it. To be honest, I'm still not sure whether to I should be glad that they removed the gateway :man_shrugging: 

* If the "violate sender's wishes" option is picked: this is pretty bad. IMHO, in the "group conversations" setting, the hierarchy of threats goes like "careless team member" > "malevolent team member" > "external threat". Sensible retention policies are good at mitigating the first point (and sometimes the third too), but if enough people are using alternative clients that _don't_ support those policies, we lose this protection. On the other hand, if the number of people using Bitlbee-like clients is insignificant, then it's unclear whether implementing support for such clients was worth it.

There are probably some design decisions here that would let us (mostly) have the best of both worlds, but I don't currently see them. (The other option is to base the gateway on a more advanced transport, but even XMPP doesn't have the ability to force clients to delete messages.)

**Comment by libBletchley** [comment]
@neongreen 

I have a problem with ppl relying on expiring messages, because that can always be abused.  When a Protonmail user sends a timed email, the expiry is not only ignored by all MUAs, but recipients can always take a screen shot. Users *cannot* have any reasonable expectation that expiry is honored. It's impossible from a security standpoint. Apart from screen shots, couldn't any 3rd-party Wire client developer decide not to honor expiry? There's also situations where the timed msg clock is frozen (when the window is not in focus, yet visible).

Infosec experts laugh at expiry.

So why have it at all? The answer is convenience. It's convenient for keeping an uncluttered client. So it's good to have expiry. But IMO it does users a disservice to let them think that it's a guaranteed security mechanism.

In the end, it still offers some security when the recipient honors the suggestion. But senders must accept that the recipient is ultimately in control of this.  I would clarify this by not strictly calling it a "timed message", but rather something like "suggested retention", b/c a malicious recipient can always force persistence.

I would go further as well, and actually give all users the choice to honor expiry. Since the sender is not in control, the illusion of control is in itself a vulnerability. Having that transparent option to dishonor expiry will make it clear that the recipient is ultimately in control of that anyway. That should be done regardless of whether gateways & 3rd party tools emerge.

**Comment by neongreen** [comment]
@libBletchley I understand your point. I can also relate to the feeling
that giving a false sense of security creates a vulnerability in itself and
should be avoided.

Ultimately, my opinion boils down to:

* whether expiring messages increase security (because they help to
increase data retention rates for cooperating clients) or decrease security
(because they give users a false sense of security and control) is an
empirical question;

* and it's one that neither of us seem to have good data/evidence to
resolve.

(Just to make it clear, this is *my* opinion and not Wire's official stance
or whatever. I'm not the one calling the shots.)

If you disagree with using this framework and instead believe that an
ideological stance should be taken, then I'd like to hear why.

I would also be curious to find out whether you think that (convenience
aside) adding a prominent checkbox "dishonor expiry" to the official
clients would increase, or decrease the number and severity of information
leaks. (Full disclosure: my gut feeling is "increase", and I'm wary of
implementing a Bitlbee interface for the very same reason.)

If you have data or studies on this or related topic (e.g. what are users'
actual expectations about expiring messages), I'd *love* to learn about
them and would appreciate any links or pointers.

Finally, another interesting thing to think about is whether we can employ
some technological solution to get what we both want. For instance, mobile
Chrome has incognito node, but it also has a warning showing up literally
every time you open an incognito tab. Displaying a warning that says
"beware of people with alternative clients and/or very good memory"
whenever timed messages are enabled could be a win-win feature, though the
question of whether alternative clients should be officially supported
remains an open question 🙂

On Sun, Jul 8, 2018, 21:55 libBletchley <notifications@github.com> wrote:

> @neongreen <https://github.com/neongreen>
>
> I have a problem with ppl relying on expiring messages, because that can
> always be abused. When a Protonmail user sends a timed email, the expiry is
> not only ignored by all MUAs, but recipients can always take a screen shot.
> Users *cannot* have any reasonable expectation that expiry is honored.
> It's impossible from a security standpoint. Apart from screen shots,
> couldn't any 3rd-party Wire client developer decide not to honor expiry?
> There's also situations where the timed msg clock is frozen (when the
> window is not in focus, yet visible).
>
> Infosec experts laugh at expiry.
>
> So why have it at all? The answer is convenience. It's convenient for
> keeping an uncluttered client. So it's good to have expiry. But IMO it does
> users a disservice to let them think that it's a guaranteed security
> mechanism.
>
> In the end, it still offers some security when the recipient honors the
> suggestion. But senders must accept that the recipient is ultimately in
> control of this. I would clarify this by not strictly calling it a "timed
> message", but rather something like "suggested retention", b/c a malicious
> recipient can always force persistence.
>
> I would go further as well, and actually give all users the choice to
> honor expiry. Since the sender is not in control, l
>
 because you were mentioned.

**Comment by neongreen** [comment]
@libBletchley I understand your point. I can also relate to the feeling
that giving a false sense of security creates a vulnerability in itself and
should be avoided.

Ultimately, my opinion boils down to:

* whether expiring messages increase security (because they help to
increase data retention rates for cooperating clients) or decrease security
(because they give users a false sense of security and control) is an
empirical question;

* and it's one that neither of us seem to have good data/evidence to
resolve. 

(Just to make it clear, this is *my* opinion and not Wire's official stance
or whatever. I'm not the one calling the shots.)

If you disagree with using this framework and instead believe that an
ideological stance should be taken, then I'd like to hear why.

I would also be curious to find out whether you think that (convenience
aside) adding a prominent checkbox "dishonor expiry" to the official
clients would increase, or decrease the number and severity of information
leaks. (Full disclosure: my gut feeling is "increase", and I'm wary of
implementing a Bitlbee interface for the very same reason.)

If you have data or studies on this or related topic (e.g. what are users'
actual expectations about expiring messages), I'd *love* to learn about
them and would appreciate any links or pointers.

Finally, another interesting thing to think about is whether we can employ
some technological solution to get what we both want. For instance, mobile
Chrome has incognito node, but it also has a warning showing up literally
every time you open an incognito tab. Displaying a warning that says
"beware of people with alternative clients and/or very good memory"
whenever timed messages are enabled could be a win-win feature, though the
question of whether alternative clients should be officially supported
remains an open question 🙂

**Comment by libBletchley** [comment]
> I would also be curious to find out whether you think that (convenience
aside) adding a prominent checkbox "dishonor expiry" to the official
clients would increase, or decrease the number and severity of information
leaks. 

I think a dishonor expiry option would have the effect of causing some leaks while preventing other leaks. The net effect would probably be an overall increase.

OTOH, the count of leaks is not the only thing to consider.  If a leak happens due to a recipient dishonoring expiry, the responsibility for that leak falls entirely on the shoulders of the recipient.  If a leak happens because the sender invested too much trust in the expiry mechanism, the fault of that is on the application developers who created a mechanism that is not as robust as it appears, to some extent.

One principle that's being overlooked so far is that an application works to serve its user wholly and exclusively.  Few examples:

**pale moon**
Consider the Pale Moon browser (https://github.com/MoonchildProductions/Pale-Moon) which feeds ad revenue to its creator (@MoonchildProductions).  Someone created an ad blocker extension for Pale Moon, and @mattatobin blocked the deployment of that extension calling it "malware".  This is a conflict of interest, and in the end the app user's best interests are not being served. 

**tor browser**
Developers of the Tor browser were told they should stop showing the padlock for websites that proxy through cloudflare because users were being mislead about the security of the MitMd connection.  The developers response was to side with website owners, and say the owners of the website intend for users to see a padlock.

**Acroread**
PDFs have security switches that grant or deny various privileges like ability to print or remove a password protection.  The viewer can decide whether or not to honor the switches.  Acrobat Reader honors the switches, and pressures developers of other PDF tools to do the same.  It's really bizarre, because the viewer's purpose is to serve its user.  An Acrobat competitor can (and should) empower its user, in which case Adobe's stance is ridiculous.

For those 3 tools, the app is not working for its own user but rather someone else.  An app's user should be regarded as the exclusive master of how that app functions, and every decision should be to serve the interest of that user.

If you accept that principle, then the motivation for not offering a user the choice to dishonor expiry can only be lack of resources or interest.. otherwise the recipients instance of the app letting the sender's interest trump the user.  Of course the setting would have to default to honoring expiry b/c that is in the recipient's interest generally in most use-cases.

That said, I'm probably coming off stronger than I actually feel. I personally would not dishonor expiry given the choice, and don't see a strong need for it. But a decision to scrap an interface possibility like bitlbee on the basis of trying to work for the sender would be getting carried away with serving the senders above the users.

**Comment by wolfbeast** [comment]
>  In an effort to protect advertisers, @wolfbeast blocked the deployment of that extension calling it "malware". This is a conflict of interest, and in the end the app user's best interests are not being served.

Since you made the effort of `@mentioning` me, note the following:

I would appreciate it if you do not twist my words or imply things that are untrue.

AdNauseam was blocked because it actively harms website owners, not to "protect advertisers". By harming innocent third parties, it is considered a form of malware.
The block in Pale Moon is also a soft block and in fact has been catered to in the UI for users to decide themselves if they want to allow this kind of harmful extension or not. Extensive discussions about this have been posted on our forum to look up if you want the skinny on it.

**Comment by mattatobin** [comment]
Why am I summoned?

**Comment by libBletchley** [comment]
@wolfbeast 

The rationale for acting against the interest of the end user in any sort of conflict isn't relevant here.  But I didn't know the ban was in any practical way circumventable by the user. If the user has the ultimate control (short of hacking source code), then it was a mistake for me to use Pale Moon in the example at hand. Sorry about that.

@mattatobin 
That was a mistake.  I mentioned you in the original post, but realized it was @wolfbeast I meant to reference & so I edited.

**Comment by wolfbeast** [comment]
@libBletchley 

> The rationale ... isn't relevant here.

You _made_ it relevant by claiming I was actively blocking an extension to protect advertisers. If it's not relevant, then don't make such statements, please, as it serves no purpose but to paint someone black.

> I didn't know the ban was in any practical way circumventable by the user.

Not just circumventable. It's been made very low effort to do so. Maybe next time it would serve to actually verify something before you want to make it an example for argumentation :smile:
![addon-sec-level-palemoon](https://user-images.githubusercontent.com/3359132/43050381-fa2bbc8e-8e07-11e8-841b-f3b549f334b4.png)

That said, apology accepted - hopefully better in the future. (please refrain from `@mention`ing me again unless you need more info)

**Comment by gregor** [comment]
As this thread is going off topic and personal I am going ahead and lock it. The changes to the feature have been deployed and we are happy as is. We will continue to monitor feedback related to us via our usual CS feedback channels and on social media but have no plans on touching this area of the product at this time.
