### ISSUE TITLE
Video resolution is only 640x480 (4:3)

### ISSUE THREAD

**Issue by RebelCoderRU** [wireapp/wire-desktop#631]
Video calls on Linux still don't work properly.

Video Calls:
Linux <-> Linux,
Linux <-> Windows,
Linux <-> Android

All platforms are always in 4:3 and around 640x480 resolution. In both cases broadband speed was 100 Mbit/s Up and Down. All 3 people have 1080p capable WebCams from Logitech. Hangouts, Jitsi Meet and Skype go to 720p, 16:9 right away, and Skype us to 1080p after 20 secs.

```
speedtest
Retrieving speedtest.net configuration...
Testing from 2Kom (46.188.60.136)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Beeline (Moscow) [6.95 km]: 4.802 ms
Testing download speed................................................................................
Download: 93.47 Mbit/s
Testing upload speed....................................................................................................
Upload: 93.06 Mbit/s
```
We have tried all combinations: wire desktop app (latest from the repos), wire web app.
Is this something you will fix soon? As we have to keep going back to services that just work and keep reporting bugs here, which we don't have to do with other software.

**Comment by lipis** [comment]
Which flavor of Linux are you using?

**Comment by RebelCoderRU** [comment]
I am on Debian 9 and My partner is on Debian 8. Debain 9 - Windows or Debian 9 - android, same result.

**Comment by agurenko** [comment]
I can relate to 4:3 ratio, having same problem, by default it's zoomed (which I only recently learned) and if you zoom out it's not 16:9. I also have Logitech cameras on both end (C910 and C920). Not sure how you can see actual resolution transmitted?

I'm on Fedora connecting with Windows machine.

**Comment by RebelCoderRU** [comment]
@agurenko Yes, you are exactly right. It is 4:3 and zoomed in and can be zoomed out. 

> Not sure how you can see actual resolution transmitted?

It is very easy. I am doing video calls since MSN Messenger as I travel a lot. I can easily spot and differentiate resolutions of 720p and up from 640x480 right away. Linux Wire only receives and sends 4:3 and in 640x480. Using Skype on Linux at the same time - BIG difference, and it is running in 1280x720 (720p).

**Comment by mythsunwind** [comment]
@RebelCoderRU Hi, can you explain the issue you opened a bit more? What does "still don't work properly" mean? Does it mean you are just not satisfied with the resolution of 640x480 or does it mean the call is not connecting or breaks up? Do you have problems with audio or video or the connection?

**Comment by agurenko** [comment]
@RebelCoderRU I have not tried Skype in a long time, but when I used Hangouts and switched to Wire I have not seem drop in quality to be honest, I'll try to compare with Jitsu today out of curiosity :)

**Comment by RebelCoderRU** [comment]
@mythsunwind Hi!

>  still don't work properly

This means, that the app has been out for so long now and still has problems with **_THE BASIC_**
functionality. You have the CPU power, the bandwidth and webcam, and still delvers video calls of 10 years ago. 

I have been trying to switch to Wire everyone I know and we still have to go back to other services as they have much better video call quality. This slows down the transition to Wire actually.

**Comment by RebelCoderRU** [comment]
@agurenko Difference in Hangouts vs Wire on Linux is **HUGE** and can easily bee seen. Variable and auto-adjustable 720p resolution in Hangouts vs Wire's 4:3, 640x480. If you say it is the same quality, your screenshots would help actually.

**Comment by agurenko** [comment]
@RebelCoderRU I'll do some testing tonight when I get home (I don't have good camera at work) and will compare, granted I don't have very good upload speed at this moment (3 mbps only), but should be enough for 720p, considering QOS priority for video traffic.

**Comment by gregor** [comment]
Video resolution is currently hardcoded to limit bandwith with mobile use cases in https://github.com/wireapp/wire-webapp/blob/dev/app/script/media/MediaStreamHandler.js#L190.
This was a deliberate decision keeping our mobile first user base in mind. Smarter approaches with adaptive resolution depending on remote client capabilities and available network bandwith have been thought about since the beginning but we never had the resources to actively implement these across platforms.

We opt for a higher resolution when you share your screen to improve readibility and because of the desktop first of this feature.

@jspittka

**Comment by agurenko** [comment]
@gregor maybe it's worth adding a control to force quality?

**Comment by RebelCoderRU** [comment]
@gregor So Linux is not getting it ? Or am I reading this wrong ? I mean, this is THE BASIC functional and it is kind of broken. Yes, Screen sharing does get 16:9, not that high res too, but how does this help us to make advertised HD Video Calls ?

**Comment by gregor** [comment]
This is not Linux specific but true for all platforms. The settings is aligned between mobile and desktop platforms. We will look into improving video quality in a more granular approach that allows desktop platforms to service higher resolutions based on the remote client capabilities in the future without a committed timeline.

**Comment by agurenko** [comment]
@RebelCoderRU so I've finally did a testing between Wire (desktop apps and a web), Hangouts, Jitsi, Skype (desktop apps). Not only Wire indeed is the only service that uses 4:3, it's the only service that does not focus ( @gregor @mythsunwind should I open a separate bug ), so face is blurred in addition to the quality. It's still better quality than Skype (video-wise), I don't know what they are doing, but it's just suck. Jitsi and Hangouts gives exactly the same picture, like no difference at all being 1280x720. Granted Wire give the best audio quality.

**Comment by Strit** [comment]
I don't really see the point of having HD 16:9 video in a video chat with someone. But I can see it being an issue if you wanna use Wire for something like podcasting (no idea why), where you take the video feed from someone and put it into an overlay, to stream it out.

But that is not was Wire is meant for.

**Comment by maximbaz** [comment]
Why not? If hardware allowed, I would gladly see my friends and family in 4k resolution.

**Comment by agurenko** [comment]
@Strit easy example is when there is more than one person in a frame? You don't want to smoosh together because some app cuts it to 4:3 and it's not exactly the point. Cropping video also removes bottom and up from the video, it's sooooo annoying, because what you see is different from what people thinks you see.

**Comment by Strit** [comment]
Don't get me wrong. It's a great "Nice-to-have". No doubt about it.

**Comment by agurenko** [comment]
@Strit actually this is more like "long overdue" and with auto-focus issues combined kind of sums up to a ... I don't want to say poor experience, because it's not that bad and much more stable than some competitors, but weird experience? Or actually misleading, that's a good word here.

**Comment by Strit** [comment]
@agurenko I haven't seen them stating the video resulotion and aspect ratio anywhere, so it's hardly misleading.
It being more stable than the competitors could be because the competitors try using HD video on cellphone connections and Wire does not?
What's wrong with weird? :smile:

**Comment by agurenko** [comment]
@Strit well, since we're down this road... I mean how many webcams are shooting in 4:3? It's a rhetorical... so do you expect it to shoot in 16:9 in all video-chat apps? Probably yes. Funny enough, I just went through the web-site, there is no mentioning of HD video anywhere, so probably yes, it was another assumption that we have these days. I actually don't have any problems with HD on my phone connection, it's the desktop that disappoints me, being connected over cable, powerful CPU and getting quality lower than my mobile phone provides sometimes :)

**Comment by mythsunwind** [comment]
As much as i like these discussion and as much I second your opinion, this might not be the right place, because this is a bug tracker and not a forum. The developers get informed about every new message on here, so we are aware of this restriction and we will look into improving video quality ;)

**Comment by gregor** [comment]
We have heard the feedback loud and clear. There are no immediate plans to increase the video calling resolution or add an adaptive mode based on your connection quality and remove side capabilities. These will be considered and continuously reprioritized though. I will go ahead and close this request as we are going to track this internally.

**Comment by matthiasg** [comment]
@gregor you mentioned resolution is increased when you share your screen. Honestly I cannot see that, the screen sharing resolution is very very bad, basically unusable for sharing text or code. It looks like a nearest pixel sampled 800x600 or less, then scaled up via bilinear filtering on target screen. See picture below. This is from Windows to Mac both directions with typical high res screens (

Looking at the code (which was improved since last I looked) it seems wire is hardcoded to HD (1280x720) as constraints but the sampling seems linear which destroys text (see below). Further investigation is required but it is important to sample the entire screen and then scale it down proportionally for transfer.

![wire](https://user-images.githubusercontent.com/231889/37644914-850586cc-2c25-11e8-8178-fdd668398322.png)

Contraints: https://github.com/wireapp/wire-webapp/blob/d960ff661c4c8a5c4e887aeafb45b4858bf36dec/app/script/media/MediaConstraintsHandler.js#L39

Configuration: https://github.com/wireapp/wire-webapp/blob/d960ff661c4c8a5c4e887aeafb45b4858bf36dec/app/script/media/MediaConstraintsHandler.js#L109
