### ISSUE TITLE
Issue section for /wire-android/ has been closed.

### ISSUE THREAD

**Issue by nostitos** [wireapp/wire-desktop#6590]
Really?

https://github.com/wireapp/wire-android

**Comment by Sledge-Hammer** [comment]
Considering that Android has the largest mobile market share and it's pure madness to support every other platform except it,  I can think of only 2 possibilities:

1) They'll completely drop the support for the free apps on every platform and focus only on the paid versions
2) They're planning to rewrite the Android version of the app from scratch and have decided it's pointless to patch the current one any longer

**Comment by kolAflash** [comment]
There's a new Android app 4.0. But it has no issue section either.  
https://github.com/wireapp/wire-android-reloaded  
It's not yet on [F-Droid](https://f-droid.org/de/packages/com.wire/). But you can download it from [GitHub](https://github.com/wireapp/wire-android-reloaded/releases/tag/v4.1.2). I just got the update on my phone from the PlayStore.

It's a pity there's no issue section. Because guess what: New app, new bugs!  
First thing is, that some of my contacts lost all message history. And it seems you can't import chat history backups from Wire versions below 4.0.

**Comment by nostitos** [comment]
Bug aside the new app is missing about a dozen essential features.

**Comment by tlebon** [comment]
@tmspzz @vitorhugods maybe can comment on this topic.
