### ISSUE TITLE
Bug/Improvement: audio dropout switching from screensharing to webcam and vice versa

### ISSUE THREAD

**Issue by alexleonard** [wireapp/wire-desktop#677]
Wire Version: 2.12.2729
Wire for Web Version: 
OS: Windows 10 Pro Version 1703, Build 15063.296
Do you have an antivirus software installed: Windows Defender Only

What steps will reproduce the problem?
1. Start a video call
2. Switch to screen sharing (and back again)

What is the expected result?
The recipient of the call should hear me talking whilst the switch is occuring.

What happens instead?
The audio drops-out for the recipient of the call whilst the video mode is changed.

This happened both ways (when the caller switched to screen sharing I could not hear him momentarily.

**Comment by gregor** [comment]
This is a limitation of the current implementation and is not going to change until Chrome finally supports RTCRtpSender.replaceTrack.

Only then can we replace media streams without the need for a full renegotiation on the peer connection. Due to compatibility issues with our own calling libraray based on WebRTC on the mobile clients we opted for a full tear down and fresh negotiation on a new peer connection until then.
