### ISSUE TITLE
Dutch locale

### ISSUE THREAD

**Issue by keunes** [wireapp/wire-desktop#686]
Hi all,

I just installed the Wire app for Windows and couldn't find Dutch in the list with languages. On CrowdIn it seems the [Dutch translation](https://crowdin.com/project/wire-cs/nl#) for the desktop project is a full 100%, however. Any clue as to when Dutch may be available in the apps?

**Comment by gregor** [comment]
@keunes Thanks for your interesting in localized version of Wire. We can only add a language to the list when both desktop and webapp projects are at a full 100%, since all the in app strings are handled by the "webapp" part of our Electron based approach. The webapp is at 94% as of now. If you contribute the remaining percentages, we will include it with the next release of the webapp within a week or two and expose the language on desktop with the next release there on each platform - which will take longer.

**Comment by keunes** [comment]
Allright. All strings translated except those with questions. Hope we can get it done before the webapp release. 👍

**Comment by gregor** [comment]
Hope I could answer all your questions.

**Comment by keunes** [comment]
Thanks. All is done now.
Next: wait and see 👍

**Comment by gregor** [comment]
Dutch was just merged into the webapp. https://github.com/wireapp/wire-webapp/pull/1391
