### ISSUE TITLE
multiple instances of wire running

### ISSUE THREAD

**Issue by DeanCollins** [wireapp/wire-desktop#7]
problem with the @wire app in (win7 64 though not sure if win variant specific) basically when you open processes window it seems to after a few hours of running have about 5 or 6 wire instances running

**Comment by tmikaeld** [comment]
This is probably because every chat/call/session is in it's own process due to Chromium sandboxing.

Though a developer should answer this more definitively.

**Comment by bennyn** [comment]
@DeanCollins Are you talking about Windows desktop process? Can you please provide a screenshot?

**Comment by DeanCollins** [comment]
Yes to windows desktop process. Sorry cant provide screenshot (I ended up deleting wire from my desktop).

**Comment by bennyn** [comment]
@DeanCollins 😢 

Did it look like this?

![unbenannt](https://cloud.githubusercontent.com/assets/469989/18207057/bcb04ee4-7129-11e6-9ff7-de67e13cad42.PNG)

**Comment by DeanCollins** [comment]
not like that, I use Win 7 but yes there were a number of instances running at the same time if left for a few hours.

**Comment by bennyn** [comment]
Ok, we will investigate...

**Comment by bennyn** [comment]
Our app is based on [Electron](http://electron.atom.io/). 

Electron will run 3 processes. That's because of Chromium's multi-process architecture. For details see: 
- https://www.chromium.org/developers/design-documents/multi-process-architecture
- https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md

Source: https://github.com/electron/electron/issues/2437#issuecomment-128416641

Having 5-6 instances was related to an issue with our app (when there was an app update in the background). We fixed that with version 2.10.2652 (August 24, 2016).

Would be happy to see you again: https://wire.com/download/ :smiley:

**Comment by DeanCollins** [comment]
thanks for the update, will download now.
