### ISSUE TITLE
Wire desktop doesn't refresh conversations when coming out of standby

### ISSUE THREAD

**Issue by msbentley** [wireapp/wire-desktop#742]
Wire Version: 2.13.2741
Wire for Web Version: 2017.06.28.1513
OS: ubuntu 17.04 x64
Do you have an antivirus software installed: No

What steps will reproduce the problem?
1. Set computer in standby
2. Have a conversation on another device
3. Wake up computer

What is the expected result?

Wire Desktop will refresh conversations.

What happens instead?

Nothing - if Wire is restarted, then conversations are refreshed.

**Comment by Sethox** [comment]
A good suggestion would be a manual refresh, for conversations and contacts (so every contact and groups gets refreshed).

**Comment by gregor** [comment]
We are tracking a few scenarios where the refresh after standby fails. Due to the general nature of this issue reported here I am going ahead with closing it. Be assured that we are working on improving the reliability in this area. Also thank you very much for the suggestion to add a manual refresh option to the disconnect banner, which we have noted down.
