### ISSUE TITLE
 Media does not arrive on desktop app, especially videos

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire-desktop#744]
Cross-post of: https://github.com/wireapp/wire-ios/issues/1092  

Especially when the sender has a poor internet connection, it seems that there are issues with media being delivered to my desktop app. Usually, after a long wait and a loading screen on my phone the media does show up there, but my desktop Wire client doesn't show any incoming media at all. Not even the loading sign.

**Comment by mythsunwind** [comment]
Hi, thank you for your report. The issue is known by us and we have an open ticket in our internal bug tracker.

**Comment by MadEgg** [comment]
Thanks. Do you know anything more about the cause and the effects? Is this issue limited to the web / desktop clients or could it happen that the mobile apps do not receive media either?

**Comment by mythsunwind** [comment]
The bug usually happens when a mobile device is on a bad connection. When you send a video, iOS client is sending 3 different messages (all encrypted): The metadata of the file (name, etc.), the preview image, and the file itself. The issue with webapp and desktop client is currently that it processes the messages incorrectly when they do not arrive in the above order and therefor shows nothing at all. The reason for the messages to arrive in different order could be a bad connection or differences in encryption/decryption timing. It is not unusual but in a testing environment this issue is hard to spot.

**Comment by gregor** [comment]
We have fixed this behavior in one of the latest webapp release (https://github.com/wireapp/wire-webapp/releases/tag/2017-08-03-15-19). All videos from mobile clients should now reliably show on the desktop app.

**Comment by grinapo** [comment]
@mythsunwind as a somewhat unrelated sidenote you can create an "unreliable" connection easily by using standard linux network delay and packet loss simulator: https://stackoverflow.com/questions/614795/simulate-delayed-and-dropped-packets-on-linux
