### ISSUE TITLE
Not receiving my own messages on second client (was offline for some weeks)

### ISSUE THREAD

**Issue by sebastianbauer** [wireapp/wire-desktop#768]
Wire Version: 2.12.2729
OS: Win 10

What steps will reproduce the problem?
1. Using Wire on Linux and Windws. Windows was offline for some weeks.
2. Opening Windows Client needs actually more than 1 hour to sync.
3. All my message couldn't be received. Have to reset the session.

I know the server just saves messages for I guess 3 months. But all those messages should work and be received correctly.

**Comment by gregor** [comment]
The e2e-encrypted messages for clients are stored for maximum 28 days on our servers. If you haven't signed in to with a device for an even longer period of time, chances are increasing that an encryption session with another has reached an unrecoverable state with each message. Reaching this states is especially likely with your own devices. Due to the nature of the encryption, we fail to decrypt messages if you have not signed in to you client for 28 days and have received an additional 1000 messages from a single client. Due to the sync of conversation read states, message delivery states, etc between your own clients, there are a lot more messages exchanged between your own devices compared to clients of other users.

While we know that we have room for improvement in performance-wise when it comes to e2ee-related tasks, the described behavior is as currently designed. I am thereby closing this issue.

I assure you, that we clearly hear you feedback and it will be considered when discussing behavior changes down the road.
