### ISSUE TITLE
Opera crash

### ISSUE THREAD

**Issue by Malaquita** [wireapp/wire-desktop#772]
Wire Version: Version 2017-07-06

What steps will reproduce the problem?
1. Opera browser open
2. Wire open
3. Receive a message
4. Opera crashes.
5. Intend to recover wire
6. Wire says the window is already open
7. Restart computer only option.

Several times, same issue.

What is the expected result?

**Comment by gregor** [comment]
This repository is related to our desktop application offerings on Windows, macOS and Linux. Issues in the webapp are tracked at https://github.com/wireapp/wire-webapp/issues.

In order to investigate the issue you described, we depend on more information provided by you. Which version of Opera are you using? Does the browser log show any errors? How do you know that receiving a message is what's crashing the browser?

FYI: If you are blocked by the tab detection after a browser crash, there is no need to restart your computer. You can either wait five minutes or clear the cookie used for the multiple tabs detection as described in https://github.com/wireapp/wire-webapp/issues/1440#issuecomment-310829158.

**Comment by Malaquita** [comment]
https://github.com/wireapp/wire-webapp/issues/871

 

I have the same problem.

___________________

+31 (0)649 711702

www.hollanddecoded.com

English Deutsch Nederlands Español Portugués বাঙালি

 
 

Gesendet: Sonntag, 09. Juli 2017 um 16:21 Uhr
Von: "Gregor Herdmann" <notifications@github.com>
An: wireapp/wire-desktop <wire-desktop@noreply.github.com>
Cc: Malaquita <malaquita@web.de>, Author <author@noreply.github.com>
Betreff: Re: [wireapp/wire-desktop] Opera crash (#772)


This repository is related to our desktop application offerings on Windows, macOS and Linux. Issues in the webapp are tracked at https://github.com/wireapp/wire-webapp/issues.

In order to investigate the issue you described, we depend on more information provided by you. Which version of Opera are you using? Does the browser log show any errors? How do you know that receiving a message is what's crashing the browser?

FYI: If you are blocked by the tab detection after a browser crash, there is no need to restart your computer. You can either wait five minutes or clear the cookie used for the multiple tabs detection as described in wireapp/wire-webapp#1440 (comment).

**Comment by Malaquita** [comment]
![image](https://user-images.githubusercontent.com/30021432/28076804-0e9b45de-6660-11e7-904e-23014e2b3861.png)

**Comment by Malaquita** [comment]
This is really annoying, every single message from wire on Opera makes a crush! Every one!

**Comment by bennyn** [comment]
@Malaquita, thanks for reaching out to us. We track this issue in https://github.com/wireapp/wire-webapp/issues/871.
