### ISSUE TITLE
[Request]  rpm for Fedora 26

### ISSUE THREAD

**Issue by 1Claude** [wireapp/wire-desktop#799]
I know we can use the AppImage, or try to build it ourselve, but it would be very cool if you could include an .rpm for Fedora.

Thanks.

**Comment by mythsunwind** [comment]
We are currently not planing to build rpm releases. One reason is that updates can only be assured with a repository and we currently do not want to maintain two different repos. Having said that we are always happy to work closely together with a fedora package maintainer if someone wants to pick it up: https://fedoraproject.org/wiki/Package_maintainer_responsibilities

**Comment by ConorIA** [comment]
https://centos.pkgs.org/7/russian-fedora-free-updates-x86_64/wire-desktop-2.13.2740-2.el7.R.x86_64.rpm.html

**Comment by 1Claude** [comment]
@ConorIA 

Too bad that rpm is not up to date.

**Comment by ConorIA** [comment]
**NO WARRANTY**

https://conoria.gitlab.io/wire-builds

- This hasn't been tested. Please report if it works.
- This won't auto-update, so you'll have to check the link again when Wire devs push a new release. 
- I think you will have to handle dependendies yourself. These are:

| Arch    | Ubuntu       | Fedora        |
|---------|--------------|---------------|
|alsa-lib | libasound2   | alsa-lib      |
|gconf    | libgconf-2-4 | GConf2        |
|libxss   | libxss1      | libXScrnSaver |
|nss      | libnss3      | nss           |

_Please report if I've missed some deps._

I'll do my best to keep this up-to-date, but please be patient or ping me if it falls behind. 
Note, I will only update for official releases with release notes, not every tag that is pushed to GitHub. The builds expire after 3 months. 

Currently, this isn't using libsodium-neon because of https://github.com/wireapp/libsodium-neon/issues/15.

**Comment by vlisivka** [comment]
@ConorIA please, provide src.rpm and/or .spec file in addition to binary-only rpm.

**Comment by ConorIA** [comment]
As posted to #67: 

@vlisivka, it's all in the open. The sources are at https://gitlab.com/ConorIA/wire-builds.
I've never used an RPM-based distro before, so I won't be able to offer any support for these builds. The builds use `electron-builder`, which doesn't provide me with a `.src.rpm` or a `.spec` file. If this is something that can be implemented, I am happy to accept a [merge request](https://gitlab.com/ConorIA/wire-builds/merge_requests). I also recommended the Russian Fedora link above, but the user complained that the rpm was out of date.
