### ISSUE TITLE
[Windows 7] Multiple processes in task manager

### ISSUE THREAD

**Issue by ElucGeek** [wireapp/wire-desktop#849]
Wire Version: 2.15.2750
OS: Windows 7
Do you have an antivirus software installed: Kaspersky Endpoint Security 10

What steps will reproduce the problem?
1. Launch Wire (at startup or manually)
2. Open task manager
3. Processes with wire.exe are adding up
4. Quit Wire -> no more process
5. Launch Wire again, it's doing the same again

What is the expected result?
Only one process running for wire.exe

What happens instead?
Processes are quickly adding up, in my case it stops with 7 processes names wire.exe, with memory allocation changing rapidly and description blinking between the "Wire" and nothing.

Please provide any additional information below. Attach a screenshot if
possible.

![image](https://user-images.githubusercontent.com/10714227/28956011-a03bbffe-78ea-11e7-96a5-2a80b74889b3.png)

![image](https://user-images.githubusercontent.com/10714227/28956030-b531b602-78ea-11e7-881c-160101a367bb.png)

**Comment by gregor** [comment]
This is by design as the desktop app is based on Electron which in turn relies on Chromium running under the hood. The Helper processes are used by the browser. With our current implementation they are needed for the app to run. We continue to update to newer Electron versions as early as possible in order to pass on performance improvments made in the browser.
