### ISSUE TITLE
Package 2.15.2751 for Linux is broken

### ISSUE THREAD

**Issue by qooob** [wireapp/wire-desktop#852]
Hi,

Thanks for amazing app.

When unpacking `.deb` package you get this error:

```Bash
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Version 2.14.2744 works fine. Please take a look.

**Comment by qooob** [comment]
File `wire-desktop.desktop` contains incorrect link containing `wire-disktop`, please check.

**Comment by ConorIA** [comment]
Not sure where `wire-disktop` could have come from. Did you download the .deb file or build it yourself?

**Comment by qooob** [comment]
I downloaded version 2.14.2744 from Releases.

**Comment by qooob** [comment]
Version 2.15.2751 I couldn't even unpack on Fedora.

**Comment by mythsunwind** [comment]
If you want to use wire on Fedora we recommend using the AppImage from https://wire.com/download instead of unpacking it yourself.

I could not reproduce the issue you describe with the deb packages from https://wire.com/download. I was also able to successfully unpack the deb package with the following commands:
```
tar -xvf wire_2.15.2751_*.deb
tar -xvf data.tar.xz
```
Which commands do you use to unpack and where did you download the package?

**Comment by qooob** [comment]
When unpacking before I tried:

`ar p wire_2.14.2744_*.deb data.tar.gz | tar zx`

Trying command in your example produced the following output:

```Bash
[me@pc wire_2.15.2751_amd64]$ tar -xvf wire_2.15.2751_*.deb
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

```

Renaming it also didn't help.

The problem is that it doesn't matter how I try, I can't unpack the latest version, neither in console nor in Archive Manager. Previous release (deb package) works just fine, again in both console (using `ar` command) and Archive Manager. 

I'm not sure what to do with _AppImage_ files?

**Comment by mythsunwind** [comment]
It looks like the archive you downloaded is corrupt. Can you check the sha256 checksum for the file:
```
# sha256sum wire_2.15.2751_amd64.deb
10dc23f64dedb5e30b275a6c5455118a4f510be837f546a841cbb2ec71be68e3  wire_2.15.2751_amd64.deb
```

AppImage is a format for portable software for Linux. It is basically a container that contains all depending libraries and therefor runs on every distribution. No extraction tools are needed. You can just run it by executing the file.

**Comment by qooob** [comment]
I just checked the checksum and all seems fine, I get the same output as you do:
```
10dc23f64dedb5e30b275a6c5455118a4f510be837f546a841cbb2ec71be68e3  wire_2.15.2751_amd64.deb
```

Why not just adding regular `.tar.gz` file? I will try AppImage, thank you.

One more question, do you support (planning to support) in-app updates, like Firefox Developer version for example or Telegram?

**Comment by mythsunwind** [comment]
We currently support update via apt repository for Ubuntu/Debian based Distributions: https://github.com/wireapp/wire-desktop/wiki/How-to-install-Wire-for-Desktop-on-Linux

No in-app updates are currently planned. There are unofficial update strategies for arch Linux https://aur.archlinux.org/packages/?O=0&SeB=nd&K=wire-desktop&outdated=&SB=n&SO=a&PP=50&do_Search=Go and Fedora https://copr.fedorainfracloud.org/coprs/conoria/wire-desktop/

We cannot support other binary builds, because depending on the distribution and libraries they will be not binary-compatible to other distributions than the ones mentioned above. AppImage is an alternative that solved the compatibility problem currently, but lags update support right now.

**Comment by qooob** [comment]
Thank you for your support and great app. Keep up!

**Comment by mythsunwind** [comment]
Thank you for taking the time to send us your comments, and please feel free to contact us again if you have additional questions.
