### ISSUE TITLE
Why are the keyboard shortcuts different from Messages?

### ISSUE THREAD

**Issue by ricburton** [wireapp/wire-desktop#884]
I am curious to find out why they are different. In Wire:

<img width="267" alt="screen shot 2017-08-16 at 08 47 45" src="https://user-images.githubusercontent.com/438160/29352717-bd58cb94-825f-11e7-9dd0-7361942da0f5.png">

In Messages:

<img width="307" alt="screen shot 2017-08-16 at 08 45 28" src="https://user-images.githubusercontent.com/438160/29352716-b9dbe0f0-825f-11e7-9d26-7f451108d5c0.png">

Is there a strong reason why? If not, I’ll submit a pull request to change them.

**Comment by gregor** [comment]
Our shortcut map is the result of a long effort by our design and UX team. I will forward your concerns for future revisions of the map. Sorry to say, a PR that changes them straight out would not be accepted at this point in time.

**Comment by ricburton** [comment]
I am curious to hear about the long effort. Why go against the grain of the platform?

**Comment by Yorgos-V** [comment]
Hello @ricburton, this is Yorgos Vourlidas from the design team. 
The reason why the keyboard shortcuts are different from Messages is because we decided to have a unified approach and maintain, as much as we can, the same combinations for Windows, MacOS and the web. We believe that this would be more convenient for our user base.
Thank you very much for sharing your concerns, it is something we will definitely keep in mind when we revisit the keyboard shortcuts logic.
