### ISSUE TITLE
Call decline not synced

### ISSUE THREAD

**Issue by zylden** [wireapp/wire-desktop#889]
Wire Version: 2.15.2751
Wire for Web Version:2017.08.08.1509
OS:ubuntu 16.04
Do you have an antivirus software installed: <This helps us to find out if there are compatibility issues with antivirus software>
no

What steps will reproduce the problem?
1.  Receive a call
2. Decline call

What is the expected result?
That the call should stop

What happens instead?
The call keeps ringing on my other connected devices. If I answer the call the other devices stop ringing, but not if i decline the call.

Please provide any additional information below. Attach a screenshot if
possible.

**Comment by gregor** [comment]
@zylden Which type of device are you declining the call on? Which type of device are your other devices? We sync the call decline across all desktop/web devices. This features is not yet implemented on mobile devices (neither sending the decline sync message nor understanding such message from a desktop client) due to technical limitations that would leak that information to the remote at this point in time.
