### ISSUE TITLE
Lack of features: Push to talk, show if people are online, etc

### ISSUE THREAD

**Issue by fourteen-eight-eight** [wireapp/wire-desktop#916]
Wire Version: 2.15.2750
Wire for Web Version: 2017.08.31.1421
OS: Windows 10
Do you have an antivirus software installed: No.

Hello, really great piece of software you've created but I feel like this would be PERFECT if you could implement the following features!

1. Push to talk with a supress key function, take a look at mumble for an example, they have a push to talk feature.

2. Show/beable to list yourself online? I find it hard to see if people are online or not when using the desktop app.

**Comment by ehodzic** [comment]
I would like to add the following to the lack of features list:

1. **Allow turning on/off (and choosing sound) for each individual notification type.** Mobile version allows one to pick a ringtone for each notification sound (call, message, ping). Desktop version does not. This is somewhat natural, since ringtones aren't a normal thing on dekstop, but not allowing to set a sound file also has the negative consequence that one cannot individually mute pings, or messages, or calls (by choosing no ringtone). Currently you are force to choose among only three options (all, none, and some). This is unnecessarily limiting and restricts the amount of custom tuning to each user's own liking and situational demands.

2. **Skins/themes.** While the mobile version does have two different themes (normal and dark) you can choose from, desktop version does not. Regardless, more colour schemes should be added to, once again, allow users to set the application's looks more to their own liking. This can only be a positive thing.

3. **Posted images are scaled to the maximum width but not height.** Images should be scaled down to some set maximum size so that whole conversation screen doesn't get covered by a single large image that is posted. Zooming function (viewing individual image in its full size) already works, so just limit the height of the image previews in conversation window to at most two text lines. In a larger conversation, no one wants to see random people spamming the chat with random images, making it difficult to follow actually text conversation.

4. **The overlay on the left is too wide.** This applies only to the desktop version. Allow it to be set to narrow mode. The narrow mode should include only user names, but not their picture, and it should be more compact with less space between the lines wasted, allowing wider lines of text in the conversation area to the right.

5. **Remove the width limit on text conversation.** Currently the desktop version has a maximum width that cannot be extended by increasing the width of the application window itself, nor is there an option to drag & extend it. Please add it as it allows more text to fit on screen in longer conversations.

**Comment by gregor** [comment]
Thank you very much for your feature requests. We have noted them down for future consideration.

Nonetheless I will go ahead and close this issue. Please remember that this is a bug tracker in a source repository and not a discussion board. All developers get notified by each comment and will spend time reading and replying to your posts. We mainly want to keep this as a place to track bugs in our code.
