### ISSUE TITLE
Check spelling while typing

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#939]
Wire offers the option to check spelling while typing. Is the spell checker a third party tool? How can spell-checking actually work when conversations are encrypted at all times?

**Comment by gregor** [comment]
Please refer to the whitepapers found at https://wire.com/privacy for this one as well. E2E-encrypted messaging ensures that messages are encrypted per device on the route from device to device. You local conversation content while you type obviously is not encrypted - otherwise you could not read and see it. We rely on an NPM package calles [spellchecker](https://www.npmjs.com/package/spellchecker) that binds to the native operating system spell checking tools.

**Comment by dandv** [comment]
For others who may land on this issue from a web search - the spell checker was removed in Jan 2019. See #2023.
