### ISSUE TITLE
Prevent automatic login

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#941]
Wire Version: 2.15.2751
Wire for Web Version: 2017.08.31.1421
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

What steps will reproduce the problem?
1. Launch Wire

What is the expected result?
I would like to have the option to manually type in my password before logging in to Wire.

What happens instead?
Currently, Wire automatically logs in and stores my login details.

**Comment by happyGNU** [comment]
I think this is very good request.
It could be added an option to automatically block wire after a while and at will. 

So in case I share my computer/phone the other person can't read my conversations without a password.  Or if I leave, and forgot to lock it, it will get locked automatically.

**Comment by mythsunwind** [comment]
In case you share a computer you should definitely consider using different logins on a the multi-user operating system which prevents access to files of the other users by rights management (for e.g. Linux or macOS).

The reason is, that an automatic logout (as suggested above) will not secure your data, because it would still be possible to get a lot of personal data from the indexeddb database.

The feature request sounds nice at first, but implementing it will result in false security considerations.

**Comment by baimafeima** [comment]
@gregor Was this closed because it was rejected or implemented?

@mythsunwind 

> The reason is, that an automatic logout (as suggested above) will not secure your data, because it would still be possible to get a lot of personal data from the indexeddb database.

I made several other requests to prevent any personal chat data to appear in a local database such as by an option to have all chat data disabled by default.
