### ISSUE TITLE
Disable email notifications upon using a new device and allow sign up without email

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-desktop#983]
Wire Version: 2.15.2751
Wire for Web Version: 2017.09.26.1300
OS: Solus 3 (https://solus-project.com/)
Do you have an antivirus software installed: no

What is the expected result?
I would like to disable all email notifications to my email account. 

What happens instead?
Currently, there is no option to do so and instead email notifications are sent out. In fact, I prefer to have the ability to sign up and use wire without any connection to my email accounts.

**Comment by gregor** [comment]
@baimafeima The new device email is a security feature that we currently do not allow to disable. This is not specific to the desktop offerings. I will share your wish internally but I would advise you to raise your concern on the main repository for general feedback found at https://github.com/wireapp/wire/issues. You can always use our mobile applications to sign up using a phone number instead of you email address.

**Comment by baimafeima** [comment]
@gregor Thanks for the feedback. Ideally, a messaging service like Wire should allow for a completely anonymous registration process, that is, without the need to indicate either emails or phone numbers.

**Comment by baimafeima** [comment]
@gregor Cross-posting and request for re-opening this issue as the other one has been in limbo for over a year and this issue is urgent as it is an anti-privacy feature. 

It's been over a year since I've raised this issue. Has there been any progress on this? The reason I ask to have email notifications upon using a new device disabled by default is because each email that is sent generates meta data - and because it's unencrypted the entire user data is in the open too. This is definitely an anti-privacy feature and should be fixed as soon as possible.
