### ISSUE TITLE
Some Notification (8) next to users and group do not disappear after clicking and looking at it.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-desktop#993]
Some Notification (8) next to users and group do not disappear after clicking and looking at it.

Restarting the app does not make then go away.

Replying to each discussion does make them go away.

**Comment by gregor** [comment]
@Transisto Are these relatively new conversations?

If so we uncovered a bug in our implementation that will be fixed with the next release.

Unfortunately the fix will not clear unread dots for conversations are already in this state as these conversations failed to properly persist timestamps in the database. You can either manually change the timestamps or send another message to the conversation and then mark it as read.

**Comment by gregor** [comment]
The release is out and this should not longer happen. Please reopen if the issue reoccurs.

Fixed by https://github.com/wireapp/wire-webapp/pull/1732
