### ISSUE TITLE
Rewrite Wire using a native framework by hosting a web view

### ISSUE THREAD

**Issue by ddobrev** [wireapp/wire-desktop#994]
Wire is slow and bloated entirely because of Electron as the latter carries the entire Chrome with it. On the other hand, I understand the effort to port the entire application to a native framework is too large. So what you could do instead is use a web view hosted in a desktop application. It's still web but this time Chrome is gone so it would be a huge step forward. In addition, in time elements of the application could be moved one by one over to native code. This way Wire would become much faster and responsive. It would also use much less battery life.
You could use Qt as the native framework, this way even the minimal native part would be shared across platforms.

Note: please spare me the listing of Slack, VS Code and others. They are all slow and bloated because this is what Electron does no matter where it's used.

**Comment by gregor** [comment]
As we have stated before the use of electron is a busines decision that allows us to cater for many platforms at the same time. We are aware the limitations. There a no plans to change this though.

**Comment by ddobrev** [comment]
@gregor you seem to pretend not to understand what I am talking about. If you use a web view, you will still share your code across all platforms, including web. But it will make the application run much faster in comparison to Electron.

**Comment by gregor** [comment]
I do understand - but we have no intention of moving away from Electron for the time being.

There is no point in raising the same argument again and again from your side. This is a decision we at Wire stand behind. If you disagree with us and don't consider our product to be performant enough to meet your needs, you are obviously free to use anything that better suits them or even build your own product.

But we will stick to our current implementation. All I am trying to do is manage your expectations. Wire desktop apps will be based on Electron for the forseeable future.

**Comment by maximbaz** [comment]
@ddobrev do you have experience with Qt to make a simple prototype? Even though Wire has no resources to invest in this, nothing prevents the community from building an alternative client. 💪

By doing event the simplest prototype, the following goals could be achieved:
- Validate by how much exactly is Qt app faster / less hungry for resources and battery.
- See if there is an interest from community to use such client (while there were requests like this in #665, #642 and #567, the [coax client](https://github.com/wireapp/coax) has only 40 stars by now and not much of a traction).
- Understand how exactly easy or difficult it is to build the client in Qt. Now it sounds simple, just a window with a webview in it, but by actually implementing it I'm sure more specific problems will be discovered. Also, what about hotkeys, native notifications, things like that...

If the performance gain is not so big, or if there isn't anyone even remotely interested in building such a prototype, or if it gets extremely difficult to implement the Qt app... well that would be a perfect answer as to why stick with Electron app. But if the prototype turns out to be a huge success with growing community interest, that would be a win 🙂

**Comment by ddobrev** [comment]
@maximbaz I'll consider creating a prototype. But if I do, I might need some assistance copying the web code to the web view. May I rely on you for questions?

**Comment by maximbaz** [comment]
I'm not currently part of the Wire team, but I was asking different questions myself about the platform here on Github, and my experience was always positive, questions were answered in great detail.

I'll also be definitely interested to test the prototype myself 🙂

**Comment by lipis** [comment]
A few more things to consider when building a new client.

- Tray icons
- Desktop icons
- Notifications
- Localisations
- Auto Updates
- Spell checker
- Apple Store
- macOS, Windows, Linux

Also how about the community of Qt?! Electron's support and iterations are super fast..

**Comment by ddobrev** [comment]
The Qt community is huge and really responsive. The framework exists for more than 20 years and has an enormous user base. I have reported many bugs to them and all major ones have been quickly resolved. In addition, I have often asked for help in their IRC channel and they have replied reasonably fast for IRC.
I have a technical question about a possible port: would it work to simply download all code and load main.js in the web view? I think not because there seem to be dependencies on modules specific to Electrom/Chromium. What do you think?

**Comment by maximbaz** [comment]
I don't think you should reuse any code from this repo, actually. Just make a webview that opens `https://app.wire.com` and that should be it.

**Comment by mythsunwind** [comment]
@ddobrev You can point your webview to app.wire.com as @maximbaz is suggesting.

As much I would like to encourage anyone to write his own prototype, I doubt that it is as easy as using a Qt webview. This is because the underlying web renderer that is used by Qt is different for each operating system. For Linux and macOS it uses the WebKit library that is installed and Windows will be using MSHTML with Trident (AFAIK EdgeHTML is not supported by Qt). And here lies the problem: Some of the web technologies we use, for e.g. IndexedDB and WebRTC, are quite new and are neither supported by MSHTML nor most WebKit versions that are currently shipped. You might not even be able to render the login page with that.

**Comment by ddobrev** [comment]
@maximbaz @mythsunwind I have created a prototype, it took me about 5 minutes. I added a web view and loaded https://app.wire.com as  advised. Logging in worked, sending messages too. I'll test a little more before uploading the code.

**Comment by ddobrev** [comment]
@maximbaz @mythsunwind the prototype works at the very least for exchanging messages with existing contacts. I would like to create a new repository with my code. I need to ask you about the following details:
1. May I get permission to create my repository under https://github.com/wireapp/ just as coax?
2. Am I allowed to use the Wire icon?
3. Am I allowed to use the Wire name?

**Comment by mythsunwind** [comment]
Maybe @raphaelrobert can help here?

**Comment by maximbaz** [comment]
I'll let folks from Wire answer these questions, but I'm very interested to learn the initial results of the prototype - what are the numbers, how much less resources does the Qt app consume? Is it even worth to continue the discussion? 🙂

**Comment by ddobrev** [comment]
@maximbaz memory is 80 MB with active usage, this is 1/5 of what Wire uses (pay attention - the Wire process itself is tolerable but it uses three additional Wire Helper processes). The average energy impact (taken from Activity Monitor on macOS) is 0.75 vs 1.02 for the official desktop client. These numbers speak for themselves so I have nothing further to add.
If you happen to have a Qt 5.9.1 installation lying around, I'd be happy to send you the source code to try, it's about 5 K uncompressed.

**Comment by raphaelrobert** [comment]
Hi @ddobrev, given that this is a prototype at this point, it is probably better if you host the source code yourself for now and the branding and name have to be different.

That doesn't mean this couldn't change in the future -- let's see how your project evolves!

**Comment by maximbaz** [comment]
@ddobrev please do share the code - maybe just publish it under your own Github account and add some brief instructions how to build and run. I'll get Qt installed, but I would need some hints on how to build the project 🙂

Since it does look promising, it would be awesome to investigate how easy or difficult it is to add features that current desktop app allows. @lipis gave a good overview of the full features list, I would selfishly say that I'm personally most interested the following two features:

1. Getting native notifications to work, so that the app is better integrated with the OS.
2. Getting `libsodium-neon` to be available for a much faster cryptography operations (comparing to javascript implementation provided by webapp, this is briefly mentioned in the README.md).

**Comment by ddobrev** [comment]
@raphaelrobert I understand. I'll do so and I'll post comments here whenever I update my work - unless you direct me to another communication channel.
@maximbaz I'll upload the code a little later today. About your points, I'll start with the menu and then notifications. About cryptography, I am telling you from now that somebody else will have to do it as I wouldn't have enough time. If my fork has a functional menu with notifications and works on Windows, Linux and macOS, it would mean I have reached feature parity and perhaps the Wire team will then consider using my approach. In this optimal case they would be the one switching to native code for encryption.

**Comment by gregor** [comment]
Just to keep your expectations reasonable: Adding a menu, notifications and running on Windows is very far away from feature parity.

The list from @lipis is a good start but there are features like screen sharing missing that are a must for us. As stated before a number of alternatives to electron where considered before we comitted to this path.

**Comment by maximbaz** [comment]
Yeah, I'm afraid this is too far from being a replacement for the official client, you shouldn't expect folks from Wire to jump on it any time soon 🙂 

But as I said before, trying to implement a couple of features will demonstrate how easy or difficult it is to build such a client in Qt - maybe it is simple, and maybe there are some features that prove to be extremely difficult (like screen sharing, maybe). 

By having your project published on Github we can also see how many people from the community would actually be interested in working on the alternative client. There have been at least 4 tickets requesting to rewrite the project, you can share the link to the Qt project in all 4 and see who is interested to contribute. Next time someone creates a similar ticket, we can also point them to this alternative client project. 🙂

**Comment by ddobrev** [comment]
@raphaelrobert @maximbaz @mythsunwind @gregor please welcome Fibre - https://gitlab.com/ddobrev/Fibre/ . I have tested it on macOS and Linux so far, it works. On Windows a Qt module is missing, I'll deal with this later. I'll keep you updated.

**Comment by tomleb** [comment]
I have actually been working on writing a Qt Wire client. Nothing published yet, not much functionality as I had to learn Qt + QML. I haven't had much time to work on it, but I'm able to send messages, I guess it's a start.
The application uses the rust library cryptobox provided by Wire and the rest is done with QML and C++.

**Comment by ddobrev** [comment]
@tomleb interesting, please do let me know when you have uploaded code. I would also suggest that if you have little time and so do I, we can work together.

**Comment by klundry** [comment]
I am very glad this is being worked on.  I really like Wire but I rarely use it on my desktop or laptop because the electron app is such a pig. It seriously takes minutes to load and become usable.  It's just a terrible desktop app and I've stopped even attempting to load it anymore which nullifies the importance of having more features.  I don't care what features it has if it's so slow that I don't even want to use it.

Looking forward to trying a leaner client.

**Comment by mythsunwind** [comment]
I will lock the conversation now. Please remember that this is a bug tracker in a source repository, not a discussion board, and all developers get notified by each comment and will take time for reading and answering questions.
