### ISSUE TITLE
Option to start desktop app in the system tray

### ISSUE THREAD

**Issue by NouGithub** [wireapp/wire-desktop#996]
Wire Version: 2.17.2813
Wire for Web Version: 9.26.1300
OS: Ubuntu 16.04

What steps will reproduce the problem?
1. Start application

What is the desired result?
- Open application without displaying the desktop window, and run it from the tray

**Comment by mythsunwind** [comment]
You can use the "Launch Wire on Startup" option in the menu to automatically start wire minimized after login or you can run `/opt/wire-desktop/wire-desktop --hidden` to start it minimized manually.

**Comment by NouGithub** [comment]
Excellent, thank you very much.  Is there a list of command line arguments I can access as a reference?

**Comment by mythsunwind** [comment]
I'm afraid not. Because Wire is based on Electron/Chrome, you might find some of the command line arguments in the Electron documentation, like this: https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

But the `--hidden` parameter is nowhere mentioned except in the source code or in the .desktop file that was created by the "Launch Wire on Startup" option.

**Comment by NouGithub** [comment]
Many thanks, I will give that a look.  Cheers for the speedy replies.
